# Introduction 

The demand for skilled data science practitioners in industry, academia, and government is rapidly growing. This book introduces concepts and skills that can help you tackle real-world data analysis challenges. It covers concepts from probability, statistical inference, linear regression and machine learning and helps you develop skills such as R programming, data wrangling with __dplyr__, data visualization with __ggplot2__, file organization with UNIX/Linux shell, version control with Git and GitHub, and reproducible document preparation with __knitr__ and R markdown. The book is divided into eight parts: __R Basics__, __Data Visualization__, __Probability__, __Statistical Inference and Modeling__, __Data Wrangling__, __Regression__, __Machine Learning__, and __Productivity Tools__. Each part has about 12 chapters, many of which include between 3-16 exercises. 

## Case studies 
Throughout the series, we use motivating case studies. For each of the concepts covered, we start by asking specific questions and answer these through data analysis. We learn the concepts as a means to answer the questions. Examples of the case studies included in the book are:

| Case Study | Concept | 
| ---- | ---| --- |
| US murder rates by state |  R basics |
| Student heights | Statistical summaries |
| Trends in world health and economics | Data Visualization | 
| The impact of vaccines on infectious disease rates | Data Visualization | 
| The financial crisis of 2007-2008 | Probability |
| Election forecasting | Statistical Inference |  
| Reported student heights | Data Wrangling | 
| Money Ball: Building a baseball team | Linear Regression |
| MNIST: Image processing hand written digits | Machine Learning |
| Movie recommendation systems | Machine Learning | 

We use the R software environment for all our analysis. You will learn R, statistical concepts, and data analysis techniques simultaneously. By working through the examples, we gain experience in R and packages such as __dplyr__,  __ggplot2__, and __caret__. In each case study, we try to realistically mimic a data scientist’s experience.

## Who will find this book useful? 

This book is meant to be a textbook for a first course in Data Science. No previous knowledge of R or statistics is necessary, although we do assume a high level of quantitative ability and some experience with programming. 
If you possess these skills, read all the chapters and complete all the exercises, you will be well positioned to perform basic data analysis tasks and you will be prepared to learn the more advanced concepts and skills needed to become an expert.

## What does this book cover? 

We start by going over the basics of R. You learn R throughout the book, but in the first chapter we go over the building blocks needed to keep learning during the rest of the book. 

Data Visualization is the topic of the following chapter. The growing availability of informative datasets and software tools has led to increased reliance on Data Visualizations in many fields. We demonstrate how to use __ggplot2__ to generate graphs and describe important Data Visualization principles.

In the third part, we introduce Probability which is useful in many contexts, in particular those that depend on data affected by chance in some way. As a result, knowledge of probability is indispensable for data analysis. Probability is also necessary to understand the topic of the next part: Statistical Inference and Modeling. Here we describe the statistical theory used by election forecasting. 

The fifth part uses several examples to familiarize the reader with Data Wrangling. Among the specific skills we learn are data import, web scrapping, using regular expressions, and reshaping data. We do this using __tidyverse__ tools.

After describing these skills and concepts, we are ready to embark on more complex data analysis tasks. In Part 7 we delineate challenges that lead us to describe linear regression and, in Chapter 8, challenges that lead us to introduce Machine Learning.

In the final chapter, we provide a brief introduction to the tools we use on a day-to-day basis in data science projects. These are RStudio, UNIX/Linux shell, Git and GitHub, and __knitr__ and R Markdown.

## What is not covered by this book? 

This book focuses on the data analysis aspects of data science. We therefore do not cover aspects related to data management or engineering. Although R programming is an essential part of the book, we do not teach more advanced topics such as data structures, optimization, and algorithm theory. Similarly, we do not cover topics such as web services, interactive graphics, parallel computing, and data streaming processing.



