# (PART) Probability, Inference, and Regression with R {-}

# Introduction to Statistics with R

The day before the 2008 presidential election, Nate Silver's FiveThirtyEight stated that "Barack Obama appears poised for a decisive electoral victory". They went further and predicted that Obama would win the election with 349 electoral votes to 189, and the popular vote by a margin of 6.1%. FiveThirtyEight also attached a probabilistic statement to their prediction claiming that Obama had a 91% chance of winning the election. The predictions were quite accurate since, in the final results, Obama won the electoral college 365 to 173 and the popular vote by a 7.2% difference. Their performance in the 2008 election brought FiveThirtyEight to the attention of political pundits and TV personalities. For years later, the week before the 2012 presidential election, FiveThirtyEight's Nate Silver was giving Obama a 90% chance of winning despite many of the experts thinking the final results would be closer. Political commentator Joe Scarborough said [during his show](https://www.youtube.com/watch?v=TbKkjm-gheY):

>>Anybody that thinks that this race is anything but a tossup right now is such an ideologue ... they're jokes.

To which Nate Silver responded via Twitter:

>> If you think it's a toss-up, let's bet. If Obama wins, you donate $1,000 to the American Red Cross. If Romney wins, I do. Deal?

In 2016, Silver was not as certain and gave Hillary Clinton only a 71% of winning, while many other forecasters were almost certain she would win. She lost. But 71% is still more than 50%. Was Mr. Silver wrong? And what does probability mean in this context anyway? Are dice being tossed somewhere? To answer these questions, we will need to learn, among other things, some probability theory. We then learn about _statistical inference_  and how it is used in election forecasting. Statistical inference builds upon probability theory.

Once we see how statistical inference is applied in the real world, we will introduce _regression_, a technique that is useful to describe the relationship between two or more variables.or instance. We will describe how this technique was used to build a baseball team with a limited budget by finding new insights by examining the relationship between player statistics and runs (points). 

The concepts covered in this part, Probability, Statistical Inference and Regression are three of the most important topics covered in a Statistics Course.
We introduce these these concepts briefly and demonstrate how they are used to answer real-world questions. For a in-depth presentation of these topics we highly recommend supplementing this part with a Probability and Statistics text book.
