# (PART) Probability {-}

# Introduction

Knowing how to compute probabilities gives you an edge in games of chance. Throughout history, many smart individuals, including famous mathematicians such as Cardano, Fermat and Pascal, spent time and energy thinking through the math of these games. As a result, Probability Theory was born. Probability  continues to be highly useful in modern games of chance. For example, in poker, we can compute the probability of winning a hand based on the cards on the table. Also, casinos rely on probability theory to develop games that guarantee a profit. 

Probability theory is useful in many other contexts and, in particular, in areas that depend on data affected by chance in some way. Knowledge of probability is therefore indispensable for data science.

In games of chance, probability has a very intuitive definition. For instance, we know what it means that the chance of a pair of dice coming up seven is 1 in 6. However, this is not the case in other contexts. Today probability is being used much more broadly with the word _probability_ commonly used in everyday language. Google's auto-complete of "What are the chances of" give us: "having twins", "rain today", "getting struck by lightning", and "getting cancer". 

The word probability is also used by election forecasters. In 2008, Nate Silver gave Obama a 94% chance of winning. In 2012 it was a 90% chance. Obama won both elections. In 2016, Silver was not as certain and gave Hillary Clinton only a 71% of winning. She lost. But 71% is still more than 50%. Was Mr. Silver wrong? And what does probability mean in this context anyway? Are dice being tossed somewhere? To answer these questions, we will need to learn, among other things, some probability theory. We cover election forecasting in the next chapter since we also need to understand the concepts of _statistical inference_, which we explain in that chapter. But keep in mind that statistical inference builds upon probability theory.

The motivation for this chapter are the circumstances surrounding the [financial crisis of 2007-2008](https://en.wikipedia.org/wiki/Financial_crisis_of_2007%E2%80%9308). This financial crisis was in part caused by underestimating the risk of certain [securities](https://en.wikipedia.org/wiki/Security_(finance)) sold by financial institutions. Specifically, the risk of mortgage-backed securities (MBS) and collateralized debt obligations (CDO) were grossly underestimated. These MBS and CDO were sold at prices that assumed most homeowners would make their monthly payments, and the probability of this not occurring was calculated as being low. A combination of factors resulted in many more defaults than were expected, which led to a price crash of these securities. As a consequence, banks lost so much money that they needed government bailouts to avoid closing down completely.

To begin to comprehend this very complicated event, we need to understand the basics of probability. We will introduce important concepts such as random variables, independence, Monte Carlo simulations, expected values, standard errors, and the Central Limit Theorem. Before using probability concepts to understand our motivating example,  we will use several examples related to games of chance since these are simple and illustrative.

