# Organizing Data with Spreadsheets

This book focuses on data analysis. Yet often a data scientist needs to collect data or work with others collecting data. Filling out a spreadsheet by hand is a practice we highly discourage and instead recommend that the process be automatized as much as possible. But sometimes you just have to do it.
In this section, we provide recommendations on how to store data in a spreadsheet. We summarize [a paper](https://www.tandfonline.com/doi/abs/10.1080/00031305.2017.1375989) by Karl Broman and Kara Woo. Here are their general recommendations. Please read the paper for important details.

    1. Be Consistent - Before you commence entering data, have a plan. Once you have a plan, be consistent and stick to it. 

    2. Choose Good Names for Things - You want the names you pick for objects, files and directories to be memorable, easy to spell, and descriptive. This is actually a hard balance to achieve and it does require time and thought. One important rule to follow is **do not use spaces**, use underscores `_` or dashes instead `-`. Also, avoid symbols, stick to letters and numbers.

    3. Write Dates as YYYY-MM-DD -  To avoid confusion, we strongly recommend using this global ISO 8601 standard.

    4. No Empty Cells - Fill in all cells and use some common code for missing data. 

    5. Put Just One Thing in a Cell - It is better to add columns to store the extra information rather than having more than one piece of information in one cell.
    6. Make it a Rectangle - The spreadsheet should be a rectangle. 
    7. Create a Data Dictionary - If you need to explain things, such as what the columns are or what the labels used for categorical variables are, do this in a separate file.
    8. No Calculations in the Raw Data Files - Excel permits you to perform calculations. Do not make this part of your spreadsheet. Code for calculations should be in a script.
    9. Do Not Use Font Color or Highlighting as Data - Most import functions are not able to import this information. Encode this information as a variable instead.
    10. Make Backups - Make regular backups of your data. 
    11. Use Data Validation to Avoid Errors - Leverage the tools in your spreadsheet software so that the process is as error-free and repetitive-stress-injury-free as possible. 
    12. Save the Data as Text Files - Save files for sharing as comma or tab delimiters.
    
## Exercises {-}


1. Pick a measurement you can take on a regular basis. For example, your daily weight or how long it takes you to run 5 miles. Keep a spreadsheet that includes the date, the hour, the measurement, and any other informative variable you think is worth keeping. Do this for 2 weeks. Then make a plot.

