<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Data Science</title>
  <meta name="description" content="This book introduces concepts and skills that can help you tackle real-world data analysis challenges. It covers concepts from probability, statistical inference, linear regression and machine learning and helps you develop skills such as R programming, data wrangling with dplyr, data visualization with ggplot2, file organization with UNIX/Linux shell, version control with GitHub, and reproducible document preparation with R markdown.">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Data Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book introduces concepts and skills that can help you tackle real-world data analysis challenges. It covers concepts from probability, statistical inference, linear regression and machine learning and helps you develop skills such as R programming, data wrangling with dplyr, data visualization with ggplot2, file organization with UNIX/Linux shell, version control with GitHub, and reproducible document preparation with R markdown." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Data Science" />
  
  <meta name="twitter:description" content="This book introduces concepts and skills that can help you tackle real-world data analysis challenges. It covers concepts from probability, statistical inference, linear regression and machine learning and helps you develop skills such as R programming, data wrangling with dplyr, data visualization with ggplot2, file organization with UNIX/Linux shell, version control with GitHub, and reproducible document preparation with R markdown." />
  

<meta name="author" content="Rafael A. Irizarry">


<meta name="date" content="2017-11-05">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="introduction.html">
<link rel="next" href="data-visualization.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Data Science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#case-studies"><i class="fa fa-check"></i>Case Studies</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#who-will-find-this-book-useful"><i class="fa fa-check"></i>Who Will Find This Book Useful?</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#what-does-this-book-cover"><i class="fa fa-check"></i>What Does This Book Cover?</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#what-is-not-covered-by-this-book"><i class="fa fa-check"></i>What is Not Covered by This Book?</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>1</b> R Basics</a><ul>
<li class="chapter" data-level="1.1" data-path="r-basics.html"><a href="r-basics.html#motivating-case-study"><i class="fa fa-check"></i><b>1.1</b> Motivating Case Study</a></li>
<li class="chapter" data-level="1.2" data-path="r-basics.html"><a href="r-basics.html#why-r"><i class="fa fa-check"></i><b>1.2</b> Why R?</a></li>
<li class="chapter" data-level="1.3" data-path="r-basics.html"><a href="r-basics.html#getting-started"><i class="fa fa-check"></i><b>1.3</b> Getting Started</a><ul>
<li class="chapter" data-level="1.3.1" data-path="r-basics.html"><a href="r-basics.html#installing-r"><i class="fa fa-check"></i><b>1.3.1</b> Installing R</a></li>
<li class="chapter" data-level="1.3.2" data-path="r-basics.html"><a href="r-basics.html#the-r-console"><i class="fa fa-check"></i><b>1.3.2</b> The R console</a></li>
<li class="chapter" data-level="1.3.3" data-path="r-basics.html"><a href="r-basics.html#scripts"><i class="fa fa-check"></i><b>1.3.3</b> Scripts</a></li>
<li class="chapter" data-level="1.3.4" data-path="r-basics.html"><a href="r-basics.html#installing-rstudio"><i class="fa fa-check"></i><b>1.3.4</b> Installing RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="r-basics.html"><a href="r-basics.html#the-r-ecosystem"><i class="fa fa-check"></i><b>1.4</b> The R ecosystem</a></li>
<li class="chapter" data-level="1.5" data-path="r-basics.html"><a href="r-basics.html#the-very-basics"><i class="fa fa-check"></i><b>1.5</b> The Very Basics</a><ul>
<li class="chapter" data-level="1.5.1" data-path="r-basics.html"><a href="r-basics.html#objects"><i class="fa fa-check"></i><b>1.5.1</b> Objects</a></li>
<li class="chapter" data-level="1.5.2" data-path="r-basics.html"><a href="r-basics.html#the-workspace"><i class="fa fa-check"></i><b>1.5.2</b> The Workspace</a></li>
<li class="chapter" data-level="1.5.3" data-path="r-basics.html"><a href="r-basics.html#functions"><i class="fa fa-check"></i><b>1.5.3</b> Functions</a></li>
<li class="chapter" data-level="1.5.4" data-path="r-basics.html"><a href="r-basics.html#other-prebuilt-objects"><i class="fa fa-check"></i><b>1.5.4</b> Other prebuilt objects</a></li>
<li class="chapter" data-level="1.5.5" data-path="r-basics.html"><a href="r-basics.html#variable-names"><i class="fa fa-check"></i><b>1.5.5</b> Variable names</a></li>
<li class="chapter" data-level="1.5.6" data-path="r-basics.html"><a href="r-basics.html#saving-your-workspace"><i class="fa fa-check"></i><b>1.5.6</b> Saving your workspace</a></li>
<li class="chapter" data-level="1.5.7" data-path="r-basics.html"><a href="r-basics.html#scripts-1"><i class="fa fa-check"></i><b>1.5.7</b> Scripts</a></li>
<li class="chapter" data-level="1.5.8" data-path="r-basics.html"><a href="r-basics.html#comments"><i class="fa fa-check"></i><b>1.5.8</b> Comments</a></li>
<li class="chapter" data-level="" data-path="r-basics.html"><a href="r-basics.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="r-basics.html"><a href="r-basics.html#data-types"><i class="fa fa-check"></i><b>1.6</b> Data types</a><ul>
<li class="chapter" data-level="1.6.1" data-path="r-basics.html"><a href="r-basics.html#data-frames"><i class="fa fa-check"></i><b>1.6.1</b> Data frames</a></li>
<li class="chapter" data-level="1.6.2" data-path="r-basics.html"><a href="r-basics.html#examining-an-object"><i class="fa fa-check"></i><b>1.6.2</b> Examining an object</a></li>
<li class="chapter" data-level="1.6.3" data-path="r-basics.html"><a href="r-basics.html#the-accessor"><i class="fa fa-check"></i><b>1.6.3</b> The accessor</a></li>
<li class="chapter" data-level="1.6.4" data-path="r-basics.html"><a href="r-basics.html#vectors-numerics-characters-and-logical"><i class="fa fa-check"></i><b>1.6.4</b> Vectors: numerics, characters, and logical</a></li>
<li class="chapter" data-level="1.6.5" data-path="r-basics.html"><a href="r-basics.html#factors"><i class="fa fa-check"></i><b>1.6.5</b> Factors</a></li>
<li class="chapter" data-level="1.6.6" data-path="r-basics.html"><a href="r-basics.html#lists"><i class="fa fa-check"></i><b>1.6.6</b> Lists</a></li>
<li class="chapter" data-level="" data-path="r-basics.html"><a href="r-basics.html#exercises-1"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="r-basics.html"><a href="r-basics.html#vectors"><i class="fa fa-check"></i><b>1.7</b> Vectors</a><ul>
<li class="chapter" data-level="1.7.1" data-path="r-basics.html"><a href="r-basics.html#creating-vectors"><i class="fa fa-check"></i><b>1.7.1</b> Creating vectors</a></li>
<li class="chapter" data-level="1.7.2" data-path="r-basics.html"><a href="r-basics.html#names"><i class="fa fa-check"></i><b>1.7.2</b> Names</a></li>
<li class="chapter" data-level="1.7.3" data-path="r-basics.html"><a href="r-basics.html#sequences"><i class="fa fa-check"></i><b>1.7.3</b> Sequences</a></li>
<li class="chapter" data-level="1.7.4" data-path="r-basics.html"><a href="r-basics.html#subsetting"><i class="fa fa-check"></i><b>1.7.4</b> Subsetting</a></li>
<li class="chapter" data-level="1.7.5" data-path="r-basics.html"><a href="r-basics.html#coercion"><i class="fa fa-check"></i><b>1.7.5</b> Coercion</a></li>
<li class="chapter" data-level="1.7.6" data-path="r-basics.html"><a href="r-basics.html#not-availables-na"><i class="fa fa-check"></i><b>1.7.6</b> Not Availables (NA)</a></li>
<li class="chapter" data-level="" data-path="r-basics.html"><a href="r-basics.html#exercises-2"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="r-basics.html"><a href="r-basics.html#sorting"><i class="fa fa-check"></i><b>1.8</b> Sorting</a><ul>
<li class="chapter" data-level="1.8.1" data-path="r-basics.html"><a href="r-basics.html#sort"><i class="fa fa-check"></i><b>1.8.1</b> <code>sort</code></a></li>
<li class="chapter" data-level="1.8.2" data-path="r-basics.html"><a href="r-basics.html#order"><i class="fa fa-check"></i><b>1.8.2</b> <code>order</code></a></li>
<li class="chapter" data-level="1.8.3" data-path="r-basics.html"><a href="r-basics.html#max-and-which.max"><i class="fa fa-check"></i><b>1.8.3</b> <code>max</code> and <code>which.max</code></a></li>
<li class="chapter" data-level="1.8.4" data-path="r-basics.html"><a href="r-basics.html#rank"><i class="fa fa-check"></i><b>1.8.4</b> <code>rank</code></a></li>
<li class="chapter" data-level="1.8.5" data-path="r-basics.html"><a href="r-basics.html#beware-of-recycling"><i class="fa fa-check"></i><b>1.8.5</b> Beware of recycling</a></li>
<li class="chapter" data-level="" data-path="r-basics.html"><a href="r-basics.html#exercise"><i class="fa fa-check"></i>Exercise</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="r-basics.html"><a href="r-basics.html#vector-arithmetics"><i class="fa fa-check"></i><b>1.9</b> Vector arithmetics</a><ul>
<li class="chapter" data-level="1.9.1" data-path="r-basics.html"><a href="r-basics.html#rescaling"><i class="fa fa-check"></i><b>1.9.1</b> Rescaling</a></li>
<li class="chapter" data-level="1.9.2" data-path="r-basics.html"><a href="r-basics.html#two-vectors"><i class="fa fa-check"></i><b>1.9.2</b> Two vectors</a></li>
<li class="chapter" data-level="" data-path="r-basics.html"><a href="r-basics.html#exercises-3"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="r-basics.html"><a href="r-basics.html#indexing"><i class="fa fa-check"></i><b>1.10</b> Indexing</a><ul>
<li class="chapter" data-level="1.10.1" data-path="r-basics.html"><a href="r-basics.html#subsetting-with-logicals"><i class="fa fa-check"></i><b>1.10.1</b> Subsetting with logicals</a></li>
<li class="chapter" data-level="1.10.2" data-path="r-basics.html"><a href="r-basics.html#logical-operators"><i class="fa fa-check"></i><b>1.10.2</b> Logical operators</a></li>
<li class="chapter" data-level="1.10.3" data-path="r-basics.html"><a href="r-basics.html#which"><i class="fa fa-check"></i><b>1.10.3</b> <code>which</code></a></li>
<li class="chapter" data-level="1.10.4" data-path="r-basics.html"><a href="r-basics.html#match"><i class="fa fa-check"></i><b>1.10.4</b> <code>match</code></a></li>
<li class="chapter" data-level="1.10.5" data-path="r-basics.html"><a href="r-basics.html#in"><i class="fa fa-check"></i><b>1.10.5</b> <code>%in%</code></a></li>
<li class="chapter" data-level="" data-path="r-basics.html"><a href="r-basics.html#exercises-4"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="r-basics.html"><a href="r-basics.html#basic-data-wrangling"><i class="fa fa-check"></i><b>1.11</b> Basic Data Wrangling</a><ul>
<li class="chapter" data-level="1.11.1" data-path="r-basics.html"><a href="r-basics.html#adding-a-column-with-mutate"><i class="fa fa-check"></i><b>1.11.1</b> Adding a column with <code>mutate</code></a></li>
<li class="chapter" data-level="1.11.2" data-path="r-basics.html"><a href="r-basics.html#subsetting-with-filter"><i class="fa fa-check"></i><b>1.11.2</b> Subsetting with <code>filter</code></a></li>
<li class="chapter" data-level="1.11.3" data-path="r-basics.html"><a href="r-basics.html#selecting-columns-with-select"><i class="fa fa-check"></i><b>1.11.3</b> Selecting columns with <code>select</code></a></li>
<li class="chapter" data-level="1.11.4" data-path="r-basics.html"><a href="r-basics.html#the-pipe"><i class="fa fa-check"></i><b>1.11.4</b> The pipe: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="1.11.5" data-path="r-basics.html"><a href="r-basics.html#creating-a-data-frame"><i class="fa fa-check"></i><b>1.11.5</b> Creating a data frame</a></li>
<li class="chapter" data-level="" data-path="r-basics.html"><a href="r-basics.html#exercises-5"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="r-basics.html"><a href="r-basics.html#basic-plots"><i class="fa fa-check"></i><b>1.12</b> Basic plots</a><ul>
<li class="chapter" data-level="1.12.1" data-path="r-basics.html"><a href="r-basics.html#scatter-plots"><i class="fa fa-check"></i><b>1.12.1</b> Scatter plots</a></li>
<li class="chapter" data-level="1.12.2" data-path="r-basics.html"><a href="r-basics.html#histograms"><i class="fa fa-check"></i><b>1.12.2</b> Histograms</a></li>
<li class="chapter" data-level="1.12.3" data-path="r-basics.html"><a href="r-basics.html#boxplot"><i class="fa fa-check"></i><b>1.12.3</b> Boxplot</a></li>
<li class="chapter" data-level="" data-path="r-basics.html"><a href="r-basics.html#exercises-6"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.13" data-path="r-basics.html"><a href="r-basics.html#importing-data"><i class="fa fa-check"></i><b>1.13</b> Importing Data</a><ul>
<li class="chapter" data-level="1.13.1" data-path="r-basics.html"><a href="r-basics.html#read.csv"><i class="fa fa-check"></i><b>1.13.1</b> <code>read.csv</code></a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="r-basics.html"><a href="r-basics.html#programming-basics"><i class="fa fa-check"></i><b>1.14</b> Programming basics</a><ul>
<li class="chapter" data-level="1.14.1" data-path="r-basics.html"><a href="r-basics.html#conditionals-expressions"><i class="fa fa-check"></i><b>1.14.1</b> Conditionals expressions</a></li>
<li class="chapter" data-level="1.14.2" data-path="r-basics.html"><a href="r-basics.html#defining-functions"><i class="fa fa-check"></i><b>1.14.2</b> Defining functions</a></li>
<li class="chapter" data-level="1.14.3" data-path="r-basics.html"><a href="r-basics.html#for-loops"><i class="fa fa-check"></i><b>1.14.3</b> For loops</a></li>
<li class="chapter" data-level="1.14.4" data-path="r-basics.html"><a href="r-basics.html#vectorization-and-functionals"><i class="fa fa-check"></i><b>1.14.4</b> Vectorization and Functionals</a></li>
<li class="chapter" data-level="1.14.5" data-path="r-basics.html"><a href="r-basics.html#map"><i class="fa fa-check"></i><b>1.14.5</b> map</a></li>
<li class="chapter" data-level="1.14.6" data-path="r-basics.html"><a href="r-basics.html#other-functions"><i class="fa fa-check"></i><b>1.14.6</b> Other functions</a></li>
<li class="chapter" data-level="" data-path="r-basics.html"><a href="r-basics.html#exercises-7"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.15" data-path="r-basics.html"><a href="r-basics.html#matrices"><i class="fa fa-check"></i><b>1.15</b> Matrices</a><ul>
<li class="chapter" data-level="1.15.1" data-path="r-basics.html"><a href="r-basics.html#accessing-matrix-values"><i class="fa fa-check"></i><b>1.15.1</b> Accessing matrix values</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>2</b> Data Visualization</a><ul>
<li class="chapter" data-level="2.1" data-path="data-visualization.html"><a href="data-visualization.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="data-visualization.html"><a href="data-visualization.html#data-types-1"><i class="fa fa-check"></i><b>2.2</b> Data types</a><ul>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#exercise-1"><i class="fa fa-check"></i>Exercise</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-visualization.html"><a href="data-visualization.html#distributions"><i class="fa fa-check"></i><b>2.3</b> Distributions</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-visualization.html"><a href="data-visualization.html#case-study-student-heights"><i class="fa fa-check"></i><b>2.3.1</b> Case study: student heights</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-visualization.html"><a href="data-visualization.html#distribution-function"><i class="fa fa-check"></i><b>2.3.2</b> Distribution function</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-visualization.html"><a href="data-visualization.html#cumulative-distribution-functions"><i class="fa fa-check"></i><b>2.3.3</b> Cumulative distribution functions</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-visualization.html"><a href="data-visualization.html#histograms-1"><i class="fa fa-check"></i><b>2.3.4</b> Histograms</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-visualization.html"><a href="data-visualization.html#smoothed-density"><i class="fa fa-check"></i><b>2.4</b> Smoothed density</a><ul>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#exercises-8"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data-visualization.html"><a href="data-visualization.html#normal-distribution"><i class="fa fa-check"></i><b>2.5</b> Normal Distribution</a><ul>
<li class="chapter" data-level="2.5.1" data-path="data-visualization.html"><a href="data-visualization.html#standardized-units"><i class="fa fa-check"></i><b>2.5.1</b> Standardized units</a></li>
<li class="chapter" data-level="2.5.2" data-path="data-visualization.html"><a href="data-visualization.html#quantile-quantile-qq-plots"><i class="fa fa-check"></i><b>2.5.2</b> Quantile-quantile QQ plots</a></li>
<li class="chapter" data-level="2.5.3" data-path="data-visualization.html"><a href="data-visualization.html#percentiles"><i class="fa fa-check"></i><b>2.5.3</b> Percentiles</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#exercises-9"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="data-visualization.html"><a href="data-visualization.html#boxplots"><i class="fa fa-check"></i><b>2.6</b> Boxplots</a></li>
<li class="chapter" data-level="2.7" data-path="data-visualization.html"><a href="data-visualization.html#case-study-are-female-student-heights-normally-distributed"><i class="fa fa-check"></i><b>2.7</b> Case study: are female student heights normally distributed?</a></li>
<li class="chapter" data-level="2.8" data-path="data-visualization.html"><a href="data-visualization.html#robust-summaries"><i class="fa fa-check"></i><b>2.8</b> Robust summaries</a><ul>
<li class="chapter" data-level="2.8.1" data-path="data-visualization.html"><a href="data-visualization.html#outliers"><i class="fa fa-check"></i><b>2.8.1</b> Outliers</a></li>
<li class="chapter" data-level="2.8.2" data-path="data-visualization.html"><a href="data-visualization.html#median"><i class="fa fa-check"></i><b>2.8.2</b> Median</a></li>
<li class="chapter" data-level="2.8.3" data-path="data-visualization.html"><a href="data-visualization.html#the-inter-quartile-range"><i class="fa fa-check"></i><b>2.8.3</b> The inter quartile range</a></li>
<li class="chapter" data-level="2.8.4" data-path="data-visualization.html"><a href="data-visualization.html#tukeys-definition-of-an-outlier"><i class="fa fa-check"></i><b>2.8.4</b> Tukey’s definition of an outlier</a></li>
<li class="chapter" data-level="2.8.5" data-path="data-visualization.html"><a href="data-visualization.html#median-absolute-deviation"><i class="fa fa-check"></i><b>2.8.5</b> Median absolute deviation</a></li>
<li class="chapter" data-level="2.8.6" data-path="data-visualization.html"><a href="data-visualization.html#self-reported-heights"><i class="fa fa-check"></i><b>2.8.6</b> Self-reported heights</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#exercises-10"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="data-visualization.html"><a href="data-visualization.html#summarizing-data-with-dplyr"><i class="fa fa-check"></i><b>2.9</b> Summarizing data with dplyr</a><ul>
<li class="chapter" data-level="2.9.1" data-path="data-visualization.html"><a href="data-visualization.html#summarize"><i class="fa fa-check"></i><b>2.9.1</b> Summarize</a></li>
<li class="chapter" data-level="2.9.2" data-path="data-visualization.html"><a href="data-visualization.html#using-the-dot-to-access-the-piped-data"><i class="fa fa-check"></i><b>2.9.2</b> Using the dot to access the piped data</a></li>
<li class="chapter" data-level="2.9.3" data-path="data-visualization.html"><a href="data-visualization.html#group-then-summarize"><i class="fa fa-check"></i><b>2.9.3</b> Group then summarize</a></li>
<li class="chapter" data-level="2.9.4" data-path="data-visualization.html"><a href="data-visualization.html#sorting-data-tables"><i class="fa fa-check"></i><b>2.9.4</b> Sorting data tables</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#exercises-11"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="data-visualization.html"><a href="data-visualization.html#a-first-introduction-to-ggplot2"><i class="fa fa-check"></i><b>2.10</b> A first introduction to ggplot2</a><ul>
<li class="chapter" data-level="2.10.1" data-path="data-visualization.html"><a href="data-visualization.html#the-cheat-sheet"><i class="fa fa-check"></i><b>2.10.1</b> The cheat sheet</a></li>
<li class="chapter" data-level="2.10.2" data-path="data-visualization.html"><a href="data-visualization.html#the-components-of-a-graph"><i class="fa fa-check"></i><b>2.10.2</b> The components of a graph</a></li>
<li class="chapter" data-level="2.10.3" data-path="data-visualization.html"><a href="data-visualization.html#the-components-of-a-graph-1"><i class="fa fa-check"></i><b>2.10.3</b> The components of a graph</a></li>
<li class="chapter" data-level="2.10.4" data-path="data-visualization.html"><a href="data-visualization.html#creating-a-blank-slate-ggplot-object"><i class="fa fa-check"></i><b>2.10.4</b> Creating a blank slate <code>ggplot</code> object</a></li>
<li class="chapter" data-level="2.10.5" data-path="data-visualization.html"><a href="data-visualization.html#layers"><i class="fa fa-check"></i><b>2.10.5</b> Layers</a></li>
<li class="chapter" data-level="2.10.6" data-path="data-visualization.html"><a href="data-visualization.html#global-aesthetic-mappings"><i class="fa fa-check"></i><b>2.10.6</b> Global aesthetic mappings</a></li>
<li class="chapter" data-level="2.10.7" data-path="data-visualization.html"><a href="data-visualization.html#scales"><i class="fa fa-check"></i><b>2.10.7</b> Scales</a></li>
<li class="chapter" data-level="2.10.8" data-path="data-visualization.html"><a href="data-visualization.html#labels-and-titles"><i class="fa fa-check"></i><b>2.10.8</b> Labels and titles</a></li>
<li class="chapter" data-level="2.10.9" data-path="data-visualization.html"><a href="data-visualization.html#adding-a-line"><i class="fa fa-check"></i><b>2.10.9</b> Adding a line</a></li>
<li class="chapter" data-level="2.10.10" data-path="data-visualization.html"><a href="data-visualization.html#other-adjustments"><i class="fa fa-check"></i><b>2.10.10</b> Other adjustments</a></li>
<li class="chapter" data-level="2.10.11" data-path="data-visualization.html"><a href="data-visualization.html#add-on-packages"><i class="fa fa-check"></i><b>2.10.11</b> Add-on packages</a></li>
<li class="chapter" data-level="2.10.12" data-path="data-visualization.html"><a href="data-visualization.html#putting-it-all-together"><i class="fa fa-check"></i><b>2.10.12</b> Putting it all together</a></li>
<li class="chapter" data-level="2.10.13" data-path="data-visualization.html"><a href="data-visualization.html#other-examples"><i class="fa fa-check"></i><b>2.10.13</b> Other examples</a></li>
<li class="chapter" data-level="2.10.14" data-path="data-visualization.html"><a href="data-visualization.html#grids-of-plots"><i class="fa fa-check"></i><b>2.10.14</b> Grids of plots</a></li>
<li class="chapter" data-level="2.10.15" data-path="data-visualization.html"><a href="data-visualization.html#summary"><i class="fa fa-check"></i><b>2.10.15</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="data-visualization.html"><a href="data-visualization.html#case-study-trends-in-world-health-and-economics"><i class="fa fa-check"></i><b>2.11</b> Case study: Trends in world health and economics</a></li>
<li class="chapter" data-level="2.12" data-path="data-visualization.html"><a href="data-visualization.html#example-1-life-expectancy-and-fertility-rates"><i class="fa fa-check"></i><b>2.12</b> Example 1: Life expectancy and fertility rates</a><ul>
<li class="chapter" data-level="2.12.1" data-path="data-visualization.html"><a href="data-visualization.html#life-expectancy-and-fertility-rates"><i class="fa fa-check"></i><b>2.12.1</b> Life expectancy and fertility rates</a></li>
<li class="chapter" data-level="2.12.2" data-path="data-visualization.html"><a href="data-visualization.html#faceting"><i class="fa fa-check"></i><b>2.12.2</b> Faceting</a></li>
<li class="chapter" data-level="2.12.3" data-path="data-visualization.html"><a href="data-visualization.html#fixed-scales-for-better-comparisons"><i class="fa fa-check"></i><b>2.12.3</b> Fixed scales for better comparisons</a></li>
<li class="chapter" data-level="2.12.4" data-path="data-visualization.html"><a href="data-visualization.html#time-series-plots"><i class="fa fa-check"></i><b>2.12.4</b> Time series plots</a></li>
<li class="chapter" data-level="2.12.5" data-path="data-visualization.html"><a href="data-visualization.html#example-2-income-distribution"><i class="fa fa-check"></i><b>2.12.5</b> Example 2: Income distribution</a></li>
<li class="chapter" data-level="2.12.6" data-path="data-visualization.html"><a href="data-visualization.html#transformations"><i class="fa fa-check"></i><b>2.12.6</b> Transformations</a></li>
<li class="chapter" data-level="2.12.7" data-path="data-visualization.html"><a href="data-visualization.html#modes"><i class="fa fa-check"></i><b>2.12.7</b> Modes</a></li>
<li class="chapter" data-level="2.12.8" data-path="data-visualization.html"><a href="data-visualization.html#stratify-and-boxplot"><i class="fa fa-check"></i><b>2.12.8</b> Stratify and boxplot</a></li>
<li class="chapter" data-level="2.12.9" data-path="data-visualization.html"><a href="data-visualization.html#comparing-distributions"><i class="fa fa-check"></i><b>2.12.9</b> Comparing distributions</a></li>
<li class="chapter" data-level="2.12.10" data-path="data-visualization.html"><a href="data-visualization.html#density-plots"><i class="fa fa-check"></i><b>2.12.10</b> Density plots</a></li>
<li class="chapter" data-level="2.12.11" data-path="data-visualization.html"><a href="data-visualization.html#accessing-computed-variables"><i class="fa fa-check"></i><b>2.12.11</b> Accessing computed variables</a></li>
<li class="chapter" data-level="2.12.12" data-path="data-visualization.html"><a href="data-visualization.html#case_when"><i class="fa fa-check"></i><b>2.12.12</b> ‘case_when’</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="data-visualization.html"><a href="data-visualization.html#ecological-fallacy"><i class="fa fa-check"></i><b>2.13</b> Ecological fallacy</a><ul>
<li class="chapter" data-level="2.13.1" data-path="data-visualization.html"><a href="data-visualization.html#show-the-data-1"><i class="fa fa-check"></i><b>2.13.1</b> Show the data</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#exercises-12"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="r-basics" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> R Basics</h1>
<p>In this book we will be using the <a href="https://cran.r-project.org/">R software environment</a> for all our analysis. Throughout the book you will learn R and data analysis techniques simultaneously. However, we need to introduce basic R syntax to get you started. In this chapter, rather than cover every R skill you need, we introduce just enough so that you can understand subsequent chapters where we provide more in depth coverage, building upon what you learn in this chapter. We find that we better retain R knowledge when we learn it to solve a specific problem.</p>
<p>In this chapter, as done throughout the book, we will use a motivating case study. We ask a specific question related to crime in United States and provide a relevant dataset. Some basic R skills will permit us to answer the motivating question.</p>
<div id="motivating-case-study" class="section level2">
<h2><span class="header-section-number">1.1</span> Motivating Case Study</h2>
<p>Imagine you live in Europe and are offered a job in a US company with many locations across all states. It is a great job but news with headlines such as <a href="http://abcnews.go.com/blogs/headlines/2012/12/us-gun-ownership-homicide-rate-higher-than-other-developed-countries/"><strong>US Gun Homicide Rate Higher Than Other Developed Countries</strong></a> have you worried. Charts like this make you worry even more:</p>
<p><img src="R/img/homocides_g8_countries_640x360_wmain.jpg" width="70%" style="display: block; margin: auto;" /></p>
<p>Or even worse, this version from <a href="https://everytownresearch.org/us-gun-violence-trends/">everytown.org</a>:</p>
<p><img src="R/img/GunTrends_murders_per_1000.png" width="70%" style="display: block; margin: auto;" /></p>
<p>But then you remember that the US is a large and diverse country with 50 very different states as well as the District of Columbia (DC).</p>
<p><img src="book_files/figure-html/unnamed-chunk-8-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>California, for example, has a larger population than Canada and 20 US states have populations larger than that of Norway. In some respects the variability across states in the US is akin to the variability across countries in Europe. Furthermore, although not included in the charts above, the murder rates in Lithuania, Ukraine, and Russia are higher than 4 per 100,000. So perhaps the news reports that worried you are too superficial. You have options of where to live and want to find out how safe each state is. We will gain some insights by examining data related to gun homicides in the US using R.</p>
<p>Before we get started with our example, we need to cover logistics as well as some of the very basic building blocks that are required to gain more advanced R skills. Be aware that the usefulness of some of these building blocks may not be immediately obvious, but later in the book you will appreciate having mastered these skills.</p>

</div>
<div id="why-r" class="section level2">
<h2><span class="header-section-number">1.2</span> Why R?</h2>
<p>R is not a programming language like C or Java. It was not created by software engineers for software development. Instead, it was developed by statisticians as an interactive environment for data analysis. You can read the full history <a href="https://pdfs.semanticscholar.org/9b48/46f192aa37ca122cfabb1ed1b59866d8bfda.pdf">here</a>. The interactivity is an indispensable feature in data science because, as you will soon learn, the ability to quickly explore data is a necessity for success in this field. However, like in other programming languages, you can save your work as scripts which can be easily executed at any moment. These scripts serve as a record of the analysis you performed, a key feature that facilitates reproducible work. If you are an expert programmer, you should not expect R to follow the conventions you are used to since you will be disappointed. If you are patient, you will come to appreciate the unequal power of R when it comes to data analysis and data visualization specifically.</p>
<p>Other attractive features of R are the following:</p>
<ol style="list-style-type: decimal">
<li>R is free and <a href="https://opensource.org/history">open source</a>.</li>
<li>It runs across all major platforms: Windows, Mac Os, UNIX/Linux.</li>
<li>Scripts and data objects can be shared seamlessly across platforms.</li>
<li>There is a large, growing, and active community of R users and, as a result, there are numerous resources for <a href="https://stats.stackexchange.com/questions/138/free-resources-for-learning-r">learning</a> and <a href="https://www.r-project.org/help.html">asking</a> <a href="https://stackoverflow.com/documentation/r/topics">questions</a>.</li>
<li>It easy for others to contribute add-ons which enables developers to share software implementations of new data science methodologies. This gives R users early access to the latest methods and to tools which are developed for a wide variety of disciplines, including ecology, molecular biology, social sciences, and geography, just to name a few examples.</li>
</ol>
</div>
<div id="getting-started" class="section level2">
<h2><span class="header-section-number">1.3</span> Getting Started</h2>
<div id="installing-r" class="section level3">
<h3><span class="header-section-number">1.3.1</span> Installing R</h3>
<p>You can download R freely from the <a href="https://cran.r-project.org/">Comprehensive R Archive Network</a> (CRAN). It is relatively straightforward, but if you need further help you can try the following resources:</p>
<ul>
<li><a href="https://github.com/genomicsclass/windows#installing-r">Installing R on Windows</a></li>
<li><a href="http://youtu.be/Icawuhf0Yqo">Installing R on Mac</a></li>
<li><a href="http://cran.r-project.org/bin/linux/ubuntu/README">Installing R on Ubuntu</a></li>
</ul>
<p>If you want to try out R without installing it, you can access a web based console such as <a href="http://www.r-fiddle.org/#/">R fiddle</a>.</p>
</div>
<div id="the-r-console" class="section level3">
<h3><span class="header-section-number">1.3.2</span> The R console</h3>
<p>Interactive data analysis usually occurs on the <em>R console</em> that executes commands as you type them. There are several ways to gain access to an R console. One way is to simply start R on your computer. The console looks something like this:</p>
<p><img src="R/img/R_console.png" width="70%" style="display: block; margin: auto;" /></p>
<p>As a quick example, try using the console to calculate a 15% tip on a meal that cost $19.71:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">0.15</span> <span class="op">*</span><span class="st"> </span><span class="fl">19.71</span>  
<span class="co">#&gt; [1] 2.96</span></code></pre></div>
<p>Note that in this book, grey boxes are used to show R code types into the R console. The symbol <code>#&gt;</code> is used to denote what the R console outputs.</p>
</div>
<div id="scripts" class="section level3">
<h3><span class="header-section-number">1.3.3</span> Scripts</h3>
<p>One of the great advantages of R over point-and-click analysis software is that you can save your work as scripts. You can edit and save these scripts using a text editor. We highly recommend working on an interactive <em>integrated development environment</em> (IDE) such as <a href="https://www.rstudio.com/">RStudio</a>, which includes an editor with many R specific features, as well as a console to execute your code, and other useful panes including one to show figures.</p>
<p><img src="R/img/rstudio.png" width="70%" style="display: block; margin: auto;" /></p>
<p>Note that most web-based R consoles also provide a pane to edit scripts, but not all permit you to save the scripts for later use.</p>
</div>
<div id="installing-rstudio" class="section level3">
<h3><span class="header-section-number">1.3.4</span> Installing RStudio</h3>
<p>Instructions on how to install RStudio are <a href="http://www.rstudio.com/products/rstudio/download/">here</a> and for Windows we have special instructions <a href="https://github.com/genomicsclass/windows">here</a>.</p>
<p>Once you install RStudio you can simply start RStudio rather than R since that program automatically starts R. But don’t be confused. R is a different piece of software and you can’t run RStudio without first installing R.</p>
<p>If you are going to follow along with RStudio as you read this book, you might consider reading the chapter five sections specifically dedicated to RStudio. RStudio includes many useful features other than providing a script editor and you want to familiarize yourself with these.</p>
<p>And remember the R scripts used to generate this book can be found on GitHub [ADD LINK].</p>
</div>
</div>
<div id="the-r-ecosystem" class="section level2">
<h2><span class="header-section-number">1.4</span> The R ecosystem</h2>
<p>The functionality provided by a fresh install of R is only a small fraction of what is possible. In fact, we refer to what you get after your first install as <em>base R</em>. The extra functionality comes from add-ons available from developers. There are currently hundreds of these available from CRAN and many others shared via other repositories such as GitHub. However because not everybody needs all available functionality, we instead make different components available via <em>packages</em>. R makes it very easy to install packages from within R. For example, to install the <code>dslabs</code> package which we use to share dataset and code related to this book you would type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;dslabs&quot;</span>)</code></pre></div>
<p>In RStudio you can navigate to the <em>Tools</em> tab and select install packages. We can then load the package into our R sessions using the <code>library</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dslabs)</code></pre></div>
<p>As you go through this book you will see that we load packages without installing them. This is because once you install a package, it remains installed and only needs to be loaded with <code>library</code>. The package remains loaded until we quit the R session. If you try to load a package and get an error, it probably means you need to install it first.</p>

</div>
<div id="the-very-basics" class="section level2">
<h2><span class="header-section-number">1.5</span> The Very Basics</h2>
<p>Before we get started with the motivating dataset we need to cover the very basics of R.</p>
<div id="objects" class="section level3">
<h3><span class="header-section-number">1.5.1</span> Objects</h3>
<p>Suppose a high school student asks us for help solving several quadratic equations of the form <span class="math inline">\(ax^2+bx+c = 0\)</span>. The quadratic formula gives us the solutions:</p>
<p><span class="math display">\[
\frac{-b - \sqrt{b^2 - 4ac}}{2a}\,\, \mbox{ and } \frac{-b + \sqrt{b^2 - 4ac}}{2a}
\]</span> which of course change depending on the values of <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, and <span class="math inline">\(c\)</span>. One advantage of programming languages is that we can define variables and write expressions with these variables, similar to how we do so in math, but obtain a numeric solution. We will write out general code for the quadratic equation below, but if we are asked to solve <span class="math inline">\(x^2 + x -1 = 0\)</span> then we define:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="dv">1</span>
b &lt;-<span class="st"> </span><span class="dv">1</span>
c &lt;-<span class="st"> </span><span class="op">-</span><span class="dv">1</span></code></pre></div>
<p>which stores the values to use later. Note that we use <code>&lt;-</code> to assign values to the variables.</p>
<p><em>Note</em>: We can assign using <code>=</code> instead of <code>&lt;-</code> but we recommend against using <code>=</code> to avoid confusion.</p>
<p>Copy and paste the code above into your console to define the three variables. Note that R does not print anything when we make this assignment. This means the objects were defined successfully. Had you made a mistake you would have received an error message.</p>
<p>To see the value stored in a variable we simply ask R to evaluate <code>a</code> and it shows the stored value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a
<span class="co">#&gt; [1] 1</span></code></pre></div>
<p>A more explicit way to ask R to show us the value stored in <code>a</code> is using <code>print</code> like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(a)
<span class="co">#&gt; [1] 1</span></code></pre></div>
<p>We use the term <em>object</em> to describe stuff that is stored in R. Variables are examples, but objects can also be more complicated entities such as functions, which are described later.</p>
</div>
<div id="the-workspace" class="section level3">
<h3><span class="header-section-number">1.5.2</span> The Workspace</h3>
<p>As we define object in the console, we are actually changing the <em>workspace</em>. You can see all the variables saved in your workspace by typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ls</span>()
<span class="co">#&gt; [1] &quot;a&quot;            &quot;b&quot;            &quot;c&quot;            &quot;fifty_states&quot;</span>
<span class="co">#&gt; [5] &quot;murders&quot;</span></code></pre></div>
<p>In RStudio the <em>Environment</em> tab shows the values</p>
<p><img src="R/img/rstudio-environment.png" width="70%" style="display: block; margin: auto;" /></p>
<p>We should see <code>a</code>, <code>b</code>, and <code>c</code>. If you try to recover the value of a variable that is not in your workspace, you receive an error. For example, if you type <code>x</code> you will receive the following message: <code>Error: object 'x' not found</code>.</p>
<p>Now since these values are saved in variables, to obtain a solution to our equation we use the quadratic formula to obtain the answer:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(<span class="op">-</span>b <span class="op">+</span><span class="st"> </span><span class="kw">sqrt</span>(b<span class="op">^</span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span>a<span class="op">*</span>c) ) <span class="op">/</span><span class="st"> </span>( <span class="dv">2</span><span class="op">*</span>a )
<span class="co">#&gt; [1] 0.618</span>
(<span class="op">-</span>b <span class="op">-</span><span class="st"> </span><span class="kw">sqrt</span>(b<span class="op">^</span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span>a<span class="op">*</span>c) ) <span class="op">/</span><span class="st"> </span>( <span class="dv">2</span><span class="op">*</span>a )
<span class="co">#&gt; [1] -1.62</span></code></pre></div>
</div>
<div id="functions" class="section level3">
<h3><span class="header-section-number">1.5.3</span> Functions</h3>
<p>Once you define variables, the data analysis process can usually be described as a series of <em>functions</em> applied to the data. R includes several predefined functions and most of the analysis pipelines we construct make extensive use of these.</p>
<p>Note that we already used the <code>install.packages</code>, <code>library</code>, and <code>ls</code> functions. And we used the function <code>sqrt</code> to solve the quadratic equation above. There are many more prebuild functions and even more can be added through packages. These functions do not appear in the workspace because you did not define them, but they are available for immediate use.</p>
<p>In general, to evaluate a function we need to uses parentheses. If you type <code>ls</code> the function is not evaluated and instead R shows you the code that defines the function. If you type <code>ls()</code> the function is evaluated and, as seen above, we see objects in the workspace.</p>
<p>Unlike <code>ls</code>, most functions require one or more <em>arguments</em>. Here is an example of how we assign object to the argument of the function <code>log</code>. Remember that we defined <code>a</code> to be 1 above:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="dv">8</span>)
<span class="co">#&gt; [1] 2.08</span>
<span class="kw">log</span>(a) 
<span class="co">#&gt; [1] 0</span></code></pre></div>
<p>You can find out what the function expects and what it does by reviewing the very useful manuals included in R. You can get help by using the <code>help</code> function like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">help</span>(<span class="st">&quot;log&quot;</span>)</code></pre></div>
<p>and for most functions we can use the shorthand:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">?log</code></pre></div>
<p>The help file will show you what arguments the function is expecting. For example, <code>log</code> needs <code>x</code> and <code>base</code> to run. However, some arguments are required and others are optional. You can determine which arguments are optional by noting, in the help document, that a default value is assigned with <code>=</code>. Defining these is optional. For example, the base of the function <code>log</code> defaults to <code>base = exp(1)</code> making <code>log</code> the natural log by default.</p>
<p>If you want a quick look at the arguments without opening the help system you can type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">args</span>(log)
<span class="co">#&gt; function (x, base = exp(1)) </span>
<span class="co">#&gt; NULL</span></code></pre></div>
<p>You can change the default values by simply assigning another object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="dv">8</span>, <span class="dt">base =</span> <span class="dv">2</span>)
<span class="co">#&gt; [1] 3</span></code></pre></div>
<p>Note that we have not been specifying the argument <code>x</code> as such:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="dt">x =</span> <span class="dv">8</span>, <span class="dt">base =</span> <span class="dv">2</span>)
<span class="co">#&gt; [1] 3</span></code></pre></div>
<p>The above code works, but we can save ourselves some typing because, if no argument name is used, R assumes you are entering arguments in the order shown in the help file or by <code>args</code>. So by not using the names, it assumes the arguments are <code>x</code> followed by <code>base</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="dv">8</span>,<span class="dv">2</span>)
<span class="co">#&gt; [1] 3</span></code></pre></div>
<p>If using the arguments’ names, then we can include them in whatever order we want:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="dt">base =</span> <span class="dv">2</span>, <span class="dt">x =</span> <span class="dv">8</span>)
<span class="co">#&gt; [1] 3</span></code></pre></div>
<p>To specify arguments we must use <code>=</code>, and cannot use <code>&lt;-</code>.</p>
<p>There are some exceptions to the rule that functions need the parenthesis to be evaluated. Among these, the most commonly used are the arithmetic and relational operators. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> <span class="op">^</span><span class="st"> </span><span class="dv">3</span>
<span class="co">#&gt; [1] 8</span></code></pre></div>
<p>You can see the arithmetic operators by typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">help</span>(<span class="st">&quot;+&quot;</span>) </code></pre></div>
<p>or</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">?<span class="st">&quot;+&quot;</span></code></pre></div>
<p>and the relational operators typing</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">help</span>(<span class="st">&quot;&gt;&quot;</span>) </code></pre></div>
<p>or</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">?<span class="st">&quot;&gt;&quot;</span></code></pre></div>
</div>
<div id="other-prebuilt-objects" class="section level3">
<h3><span class="header-section-number">1.5.4</span> Other prebuilt objects</h3>
<p>There are several datasets that are included for users to practice and test out functions. You can see all the available datasets by typing</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>()</code></pre></div>
<p>This shows you the object name for these datasets. These datasets are objects that can be used by simply typing the name, for example typing</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">co2</code></pre></div>
<p>will show you Mauna Loa atmospheric CO2 concentration data.</p>
<p>Other prebuilt objects are mathematical quantities such as the constant <span class="math inline">\(\pi\)</span> and <span class="math inline">\(\infty\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pi
<span class="co">#&gt; [1] 3.14</span>
<span class="ot">Inf</span><span class="op">+</span><span class="dv">1</span>
<span class="co">#&gt; [1] Inf</span></code></pre></div>
</div>
<div id="variable-names" class="section level3">
<h3><span class="header-section-number">1.5.5</span> Variable names</h3>
<p>Here we used the letters <em>a</em>, <em>b</em>, and <em>c</em> as variable names, but variable names can be almost anything. Some basic rules in R is that they have to start with a letter, can’t contain spaces and we avoid variables that are predefined in R, for example don’t use <code>install.packages</code> as a variable name. Don’t type <code>install.packages &lt;- 2</code>!</p>
<p>A nice convention to follow is to use meaningful words that describe what is stored, use only lower case, and use underscores as a substitute for spaces. For example, for the quadratic equations we could use something like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">solution_<span class="dv">1</span> &lt;-<span class="st"> </span>(<span class="op">-</span>b <span class="op">+</span><span class="st"> </span><span class="kw">sqrt</span>(b<span class="op">^</span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span>a<span class="op">*</span>c) ) <span class="op">/</span><span class="st"> </span>( <span class="dv">2</span><span class="op">*</span>a )
solution_<span class="dv">2</span> &lt;-<span class="st"> </span>(<span class="op">-</span>b <span class="op">-</span><span class="st"> </span><span class="kw">sqrt</span>(b<span class="op">^</span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span>a<span class="op">*</span>c) ) <span class="op">/</span><span class="st"> </span>( <span class="dv">2</span><span class="op">*</span>a )</code></pre></div>
</div>
<div id="saving-your-workspace" class="section level3">
<h3><span class="header-section-number">1.5.6</span> Saving your workspace</h3>
<p>Values remain in the workspace until you end your session or you erase them with the function <code>rm</code>. But workspaces can be saved for later use. In fact, when you quit R, the programs asks you if you want to do this. If you do, the next time you start R, the program will restore the workspace.</p>
<p>We actually recommend against saving the workspace this way because as you start working on different projects, it will become harder to keep track of what is saved. Instead we recommend you assign the workspace a specific name. You can do this by using the function <code>save</code> or <code>save.image</code>. To load you use the function <code>load</code>. When saving a workspace we recommend the suffix <code>rda</code> or <code>RData</code>. In RStudio, you can also do this by navigating to the <em>Session</em> tab and <em>Save Workspace as</em>. You can later load it using the <em>Load Workspace</em> options in the same tab. You can read the help pages on <code>save</code>, <code>save.image</code> and <code>load</code> to learn more.</p>
</div>
<div id="scripts-1" class="section level3">
<h3><span class="header-section-number">1.5.7</span> Scripts</h3>
<p>To solve another equation such as <span class="math inline">\(3x^2 + 2x -1\)</span> we can copy and paste the code above but this time redefine the variables and recompute the solution:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="dv">3</span>
b &lt;-<span class="st"> </span><span class="dv">2</span>
c &lt;-<span class="st"> </span><span class="op">-</span><span class="dv">1</span>
(<span class="op">-</span>b <span class="op">+</span><span class="st"> </span><span class="kw">sqrt</span>(b<span class="op">^</span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span>a<span class="op">*</span>c) ) <span class="op">/</span><span class="st"> </span>( <span class="dv">2</span><span class="op">*</span>a )
(<span class="op">-</span>b <span class="op">-</span><span class="st"> </span><span class="kw">sqrt</span>(b<span class="op">^</span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span>a<span class="op">*</span>c) ) <span class="op">/</span><span class="st"> </span>( <span class="dv">2</span><span class="op">*</span>a )</code></pre></div>
<p>By creating and saving a script with the code above, we would not need to retype everything each time and instead simply change the variable names. Try writing the script above into an editor and notice how much easier it is to change the variables and receive an answer.</p>
</div>
<div id="comments" class="section level3">
<h3><span class="header-section-number">1.5.8</span> Comments</h3>
<p>If a line of R code starts with the symbol <code>#</code> it is not evaluated. We can use this to write reminders of why we wrote a particular code. For example, in the script above we could add</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Code to compute solution to quadratic equation of the form ax^2 + bx + c
## define the variables
a &lt;-<span class="st"> </span><span class="dv">3</span> 
b &lt;-<span class="st"> </span><span class="dv">2</span>
c &lt;-<span class="st"> </span><span class="op">-</span><span class="dv">1</span>

## now compute the solution
(<span class="op">-</span>b <span class="op">+</span><span class="st"> </span><span class="kw">sqrt</span>(b<span class="op">^</span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span>a<span class="op">*</span>c) ) <span class="op">/</span><span class="st"> </span>( <span class="dv">2</span><span class="op">*</span>a )
(<span class="op">-</span>b <span class="op">-</span><span class="st"> </span><span class="kw">sqrt</span>(b<span class="op">^</span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span>a<span class="op">*</span>c) ) <span class="op">/</span><span class="st"> </span>( <span class="dv">2</span><span class="op">*</span>a )</code></pre></div>
</div>
<div id="exercises" class="section level3 unnumbered">
<h3>Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>What is the sum of the first 100 positive integers? There is a formula that tells us the sum of integers <span class="math inline">\(1\)</span> through <span class="math inline">\(n\)</span>. It is <span class="math inline">\(n (n-1)/2\)</span>. Define <span class="math inline">\(n=100\)</span> and then use R to compute the sum of <span class="math inline">\(1\)</span> through <span class="math inline">\(100\)</span> using the formula. What is the sum?</p></li>
<li><p>Now use the same formula to compute the sum of the integers from 1 through 1,000.</p></li>
<li><p>Look at the result of typing the following code into R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">1000</span>
x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span>, n)
<span class="kw">sum</span>(x)</code></pre></div>
<p>Based on the result, what do you think the functions <code>seq</code> and <code>sum</code> do? You can use the help system:</p>
<ol style="list-style-type: upper-alpha">
<li><code>sum</code> creates a list of numbers and <code>seq</code> adds them up.</li>
<li><code>seq</code> creates a list of numbers and <code>sum</code> adds them up.</li>
<li><code>seq</code> computes the difference between two arguments and <code>sum</code> computes the sum of 1 through 1000.</li>
<li><code>sum</code> always returns the same number</li>
</ol></li>
<li><p>In math and programming we say we evaluate a function when we replace the argument with a given number. So if we type <code>sqrt(4)</code>, we evaluate the <code>sqrt</code> function. In R you can evaluate a function inside another function. The evaluations happen from the inside out. Use one line of code to compute the log, in base 10, of the square root of 100.</p></li>
<li><p>Which of the following will always return the numeric value stored in <code>x</code>? You can try out examples and use the help system if you want.</p>
<ol style="list-style-type: upper-alpha">
<li><code>log(10^x)</code></li>
<li><code>log10(x^10)</code></li>
<li><code>log(exp(x))</code></li>
<li><code>exp(log(x, base = 2))</code></li>
</ol></li>
</ol>

</div>
</div>
<div id="data-types" class="section level2">
<h2><span class="header-section-number">1.6</span> Data types</h2>
<p>Variables in R can be of different types. For example, we need to distinguish numbers from character strings and tables from simple lists of numbers. The function <code>class</code> helps us determine what type of object we have:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="dv">2</span>
<span class="kw">class</span>(a)
<span class="co">#&gt; [1] &quot;numeric&quot;</span></code></pre></div>
<p>To work efficiently in R it is important to learn the different types of variables and what we can do with these.</p>
<div id="data-frames" class="section level3">
<h3><span class="header-section-number">1.6.1</span> Data frames</h3>
<p>Up to now, the variables we have defined are just one number. This is not very useful for storing data. The most common way of storing a dataset in R is in a <em>data frame</em>. Conceptually, we can think of a data frame as a table with rows representing observations and the different variables reported for each observation defining the columns. Data frames are particularly useful for datasets because we can combine different data types into one object.</p>
<p>We stored the data for our motivating example in a data frame. You can access this dataset by loading the <code>dslabs</code> library and loading the <code>murders</code> dataset using the <code>data</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dslabs)
<span class="kw">data</span>(murders)</code></pre></div>
<p>To see that this is in fact a data frame we type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(murders)
<span class="co">#&gt; [1] &quot;data.frame&quot;</span></code></pre></div>
</div>
<div id="examining-an-object" class="section level3">
<h3><span class="header-section-number">1.6.2</span> Examining an object</h3>
<p>The function <code>str</code> is useful to find out more about the structure of an object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(murders)
<span class="co">#&gt; &#39;data.frame&#39;:    51 obs. of  5 variables:</span>
<span class="co">#&gt;  $ state     : chr  &quot;Alabama&quot; &quot;Alaska&quot; &quot;Arizona&quot; &quot;Arkansas&quot; ...</span>
<span class="co">#&gt;  $ abb       : chr  &quot;AL&quot; &quot;AK&quot; &quot;AZ&quot; &quot;AR&quot; ...</span>
<span class="co">#&gt;  $ region    : Factor w/ 4 levels &quot;Northeast&quot;,&quot;South&quot;,..: 2 4 4 2 4 4 1 2 2 2 ...</span>
<span class="co">#&gt;  $ population: num  4779736 710231 6392017 2915918 37253956 ...</span>
<span class="co">#&gt;  $ total     : num  135 19 232 93 1257 ...</span></code></pre></div>
<p>This tells us much more about the object. We see that the table has 51 rows (50 states plus DC) and five variables. We can show the first six lines using the function <code>head</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(murders)
<span class="co">#&gt;        state abb region population total</span>
<span class="co">#&gt; 1    Alabama  AL  South    4779736   135</span>
<span class="co">#&gt; 2     Alaska  AK   West     710231    19</span>
<span class="co">#&gt; 3    Arizona  AZ   West    6392017   232</span>
<span class="co">#&gt; 4   Arkansas  AR  South    2915918    93</span>
<span class="co">#&gt; 5 California  CA   West   37253956  1257</span>
<span class="co">#&gt; 6   Colorado  CO   West    5029196    65</span></code></pre></div>
<p>In this dataset each state is considered an observation and five variables are reported for each state.</p>
<p>Before we go any further in answering our original question about different states, let’s learn more aboutthe components of this object.</p>
</div>
<div id="the-accessor" class="section level3">
<h3><span class="header-section-number">1.6.3</span> The accessor</h3>
<p>For our analysis we will need to access the different variables represented by columns included in this data frame. To access these variables we use the accessor operator <code>$</code> in the following way:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders<span class="op">$</span>population
<span class="co">#&gt;  [1]  4779736   710231  6392017  2915918 37253956  5029196  3574097</span>
<span class="co">#&gt;  [8]   897934   601723 19687653  9920000  1360301  1567582 12830632</span>
<span class="co">#&gt; [15]  6483802  3046355  2853118  4339367  4533372  1328361  5773552</span>
<span class="co">#&gt; [22]  6547629  9883640  5303925  2967297  5988927   989415  1826341</span>
<span class="co">#&gt; [29]  2700551  1316470  8791894  2059179 19378102  9535483   672591</span>
<span class="co">#&gt; [36] 11536504  3751351  3831074 12702379  1052567  4625364   814180</span>
<span class="co">#&gt; [43]  6346105 25145561  2763885   625741  8001024  6724540  1852994</span>
<span class="co">#&gt; [50]  5686986   563626</span></code></pre></div>
<p>But how did we know to use population? Above, by applying the function <code>str</code> to the object <code>murders</code>, we revealed the names for each of the five variables stored in this table. We can quickly access the variable names using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(murders)
<span class="co">#&gt; [1] &quot;state&quot;      &quot;abb&quot;        &quot;region&quot;     &quot;population&quot; &quot;total&quot;</span></code></pre></div>
<p>It is important to know that the order of the entries in <code>murders$population</code> preserves the order of the rows in our data table. This will later permit us to manipulate one variable based on the results of another. For example, we will be able to order the state names by the number of murders.</p>
<p><strong>Tip</strong>: R comes with a very nice auto-complete functionality that saves us the trouble of typing out all the names. Try typing <code>murders$p</code> then hitting the <em>tab</em> key on your keyboard. This functionality and many other useful auto-complete features are availalbe when working in RStudio.</p>
</div>
<div id="vectors-numerics-characters-and-logical" class="section level3">
<h3><span class="header-section-number">1.6.4</span> Vectors: numerics, characters, and logical</h3>
<p>Note that the object <code>murders$population</code> is not one number, but several. We call these types of objects <em>vectors</em>. A single number is technically a vector, but in general we use vectors to refer to objects with several entries. The function <code>length</code> tells you how many entries are in the vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pop &lt;-<span class="st"> </span>murders<span class="op">$</span>population
<span class="kw">length</span>(pop)
<span class="co">#&gt; [1] 51</span></code></pre></div>
<p>This particular vector is <em>numeric</em> since population sizes are numbers:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(pop)
<span class="co">#&gt; [1] &quot;numeric&quot;</span></code></pre></div>
<p>In a numeric vector, every entry must be a number.</p>
<p>To store character strings, vectors can also be of class <em>character</em>. For example, the state names are characters:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(murders<span class="op">$</span>state)
<span class="co">#&gt; [1] &quot;character&quot;</span></code></pre></div>
<p>As with numeric vectors, all entries in a character vector need to be a character.</p>
<p>Another important type are <em>logical vectors</em>. These must be either <code>TRUE</code> or <code>FALSE</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="dv">3</span> <span class="op">==</span><span class="st"> </span><span class="dv">2</span>
z
<span class="co">#&gt; [1] FALSE</span>
<span class="kw">class</span>(z)
<span class="co">#&gt; [1] &quot;logical&quot;</span></code></pre></div>
<p>Here the <code>==</code> is a relational operator asking if 3 is equal to 2. Remember that in R, if you just use one <code>=</code> you actually assign.</p>
<p>You can see the other <em>relational operators</em> by typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">?Comparison</code></pre></div>
<p>In future sections you will see how useful relational operators can be.</p>
<p><strong>Advanced</strong>: Mathematically, the values in <code>pop</code> are integers and there is an integer class in R. However, by default, numbers are assigned class numeric even when they are round integers. For example, <code>class(1)</code> returns numeric. You can turn them into class integer with <code>as.integer(1)</code> or add by adding an <code>L</code> like this: <code>1L</code>. Note the class by typing: <code>class(1L)</code></p>
</div>
<div id="factors" class="section level3">
<h3><span class="header-section-number">1.6.5</span> Factors</h3>
<p>In the <code>murders</code> dataset we might expect the region to also be a character vector. However it is not:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(murders<span class="op">$</span>region)
<span class="co">#&gt; [1] &quot;factor&quot;</span></code></pre></div>
<p>It is a <em>factor</em>. Factors are useful for storing categorical data. We can notice that there are only 4 regions by using the <code>levels</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">levels</span>(murders<span class="op">$</span>region)
<span class="co">#&gt; [1] &quot;Northeast&quot;     &quot;South&quot;         &quot;North Central&quot; &quot;West&quot;</span></code></pre></div>
<p>So, in the background, R stores these <em>levels</em> as integers and keeps a map to keep track of the labels. This is more memory efficient than storing all the characters. However, factors are also a source of confusion as they can easily be confused with characters, but behave differently in different contexts. Remember that factors and characters sometimes result in different behavior from R and that this is a common source of hard to find bugs in our code.</p>
<p>In general, we recommend avoiding factors as much as possible, although they are sometimes necessary to fit models containing categorical data.</p>
</div>
<div id="lists" class="section level3">
<h3><span class="header-section-number">1.6.6</span> Lists</h3>
<p>Data frames are a special case of <em>lists</em>. We will cover lists in more detail later, but know that they are useful because you can store any combination of different types. Below is an example of a list we created for you:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">record
<span class="co">#&gt; $name</span>
<span class="co">#&gt; [1] &quot;John Doe&quot;</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $student_id</span>
<span class="co">#&gt; [1] 1234</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $grades</span>
<span class="co">#&gt; [1] 95 82 91 97 93</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $final_grade</span>
<span class="co">#&gt; [1] &quot;A&quot;</span>
<span class="kw">class</span>(record)
<span class="co">#&gt; [1] &quot;list&quot;</span></code></pre></div>
<p>We won’t be using lists until later, but you might encounter one in your own exploration of R. For this reason we show you some basics here.</p>
<p>As with data frames, you can extract the components of a list with the accessor <code>$</code>. In fact, data frames are a type of list.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">record<span class="op">$</span>student_id
<span class="co">#&gt; [1] 1234</span></code></pre></div>
<p>We can also use double brackets like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">record[[<span class="st">&quot;student_id&quot;</span>]]
<span class="co">#&gt; [1] 1234</span></code></pre></div>
<p>You should get used to the fact that in R there are several ways to do the same thing, in particular accessing entries.</p>
</div>
<div id="exercises-1" class="section level3 unnumbered">
<h3>Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Load the US murders dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dslabs)
<span class="kw">data</span>(<span class="st">&quot;murders&quot;</span>)</code></pre></div>
<p>Use the function <code>str</code> to examine the structure of the <code>murders</code> object. We can see that this object is a data frame with 51 rows and five columns. Which of the following best describes the variables represented in this data frame:</p>
<ol style="list-style-type: upper-alpha">
<li>The 51 states</li>
<li>The murder rates for all 50 states and DC</li>
<li>The state name, the abbreviation of the state name, the state’s region, and the state’s population and total number of murders for 2010</li>
<li><code>str</code> shows no relevant information</li>
</ol></li>
<li><p>What are the column names used by the data frame for these five variables?</p></li>
<li><p>Use the accessor <code>$</code> to extract the state abbreviations and assign them to the object <code>a</code>. What is the class of this object?</p></li>
<li><p>Now use the square brackets to extract the state abbreviations and assign them to the object <code>b</code>. Use the <code>identical</code> function to determine if <code>a</code> and <code>b</code> are the same.</p></li>
<li><p>We saw that the <code>regions</code> column stores a factor. You can corroborate this by typing:</p></li>
<li><p>The function <code>table</code> takes a vector and returns the frequency of each element. You can quickly see how many states are in each region by applying this function. Use this function in one line of code to create a table of states per region.</p></li>
</ol>

</div>
</div>
<div id="vectors" class="section level2">
<h2><span class="header-section-number">1.7</span> Vectors</h2>
<p>In R, the most basic unit available to store data are <em>vectors</em>. As we have seen, complex datasets can usually be broken down into components that are vectors. For example, in a data frame each column is a vector. Here we learn more about this important class.</p>
<div id="creating-vectors" class="section level3">
<h3><span class="header-section-number">1.7.1</span> Creating vectors</h3>
<p>We can create vectors using the function <code>c</code>, which stands for concatenate. We use <code>c</code> to <em>concatenate</em> entries in the following way:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">codes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">380</span>, <span class="dv">124</span>, <span class="dv">818</span>)
codes
<span class="co">#&gt; [1] 380 124 818</span></code></pre></div>
<p>We can also create character vectors. We use the quotes to denote that the entries are characters rather than variable names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">country &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;italy&quot;</span>, <span class="st">&quot;canada&quot;</span>, <span class="st">&quot;egypt&quot;</span>)</code></pre></div>
<p>In R you can also use single quotes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">country &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;italy&#39;</span>, <span class="st">&#39;canada&#39;</span>, <span class="st">&#39;egypt&#39;</span>)</code></pre></div>
<p>But be careful not to cofuse the single quote ’ with the <em>back quote</em> `.</p>
<p>By now you should know that if you type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">country &lt;-<span class="st"> </span><span class="kw">c</span>(italy, canada, egypt)</code></pre></div>
<p>you receive an error because the variables <code>italy</code>, <code>canada</code> and <code>egypt</code> are not defined: R looks for variables with those names and returns an error.</p>
</div>
<div id="names" class="section level3">
<h3><span class="header-section-number">1.7.2</span> Names</h3>
<p>Sometimes it is useful to name the entries of a vector. For example, when defining a vector of country codes, we can use the names to connect the two:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">codes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dt">italy =</span> <span class="dv">380</span>, <span class="dt">canada =</span> <span class="dv">124</span>, <span class="dt">egypt =</span> <span class="dv">818</span>)
codes
<span class="co">#&gt;  italy canada  egypt </span>
<span class="co">#&gt;    380    124    818</span></code></pre></div>
<p>The object <code>codes</code> continues to be a numeric vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(codes)
<span class="co">#&gt; [1] &quot;numeric&quot;</span></code></pre></div>
<p>but with names:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(codes)
<span class="co">#&gt; [1] &quot;italy&quot;  &quot;canada&quot; &quot;egypt&quot;</span></code></pre></div>
<p>If the use of strings without quotes looks confusing, know that you can use the quotes as well:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">codes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;italy&quot;</span> =<span class="st"> </span><span class="dv">380</span>, <span class="st">&quot;canada&quot;</span> =<span class="st"> </span><span class="dv">124</span>, <span class="st">&quot;egypt&quot;</span> =<span class="st"> </span><span class="dv">818</span>)
codes
<span class="co">#&gt;  italy canada  egypt </span>
<span class="co">#&gt;    380    124    818</span></code></pre></div>
<p>There is no difference between this function call and the previous one. This is one of the many ways in which R is quirky compared to other languages.</p>
<p>We can also assign names using the <code>names</code> functions:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">codes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">380</span>, <span class="dv">124</span>, <span class="dv">818</span>)
country &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;italy&quot;</span>,<span class="st">&quot;canada&quot;</span>,<span class="st">&quot;egypt&quot;</span>)
<span class="kw">names</span>(codes) &lt;-<span class="st"> </span>country
codes
<span class="co">#&gt;  italy canada  egypt </span>
<span class="co">#&gt;    380    124    818</span></code></pre></div>
</div>
<div id="sequences" class="section level3">
<h3><span class="header-section-number">1.7.3</span> Sequences</h3>
<p>Another useful function for creating vectors generates sequences:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">10</span>)
<span class="co">#&gt;  [1]  1  2  3  4  5  6  7  8  9 10</span></code></pre></div>
<p>The first argument defines the start, and the second the end. The default is to go up in increments of 1, but a third argument lets us tell it how much to jump by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">10</span>, <span class="dv">2</span>)
<span class="co">#&gt; [1] 1 3 5 7 9</span></code></pre></div>
<p>If we want consecutive integers, we can use the following shorthand:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span><span class="op">:</span><span class="dv">10</span>
<span class="co">#&gt;  [1]  1  2  3  4  5  6  7  8  9 10</span></code></pre></div>
<p>When we use these function, R produces integers, not numerics, because they are typically used to index something:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>)
<span class="co">#&gt; [1] &quot;integer&quot;</span></code></pre></div>
<p>However, as soon as we create sequence including non-integer, the class changes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">10</span>))
<span class="co">#&gt; [1] &quot;integer&quot;</span>
<span class="kw">class</span>(<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">10</span>, <span class="fl">0.5</span>))
<span class="co">#&gt; [1] &quot;numeric&quot;</span></code></pre></div>
</div>
<div id="subsetting" class="section level3">
<h3><span class="header-section-number">1.7.4</span> Subsetting</h3>
<p>We use square brackets to access specific elements of a vector. For the vector <code>codes</code> we defined above, we can access the second element using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">codes[<span class="dv">2</span>]
<span class="co">#&gt; canada </span>
<span class="co">#&gt;    124</span></code></pre></div>
<p>You can get more than one entry by using a multi-entry vector as an index:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">codes[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)]
<span class="co">#&gt; italy egypt </span>
<span class="co">#&gt;   380   818</span></code></pre></div>
<p>The sequences defined above are particularly useful if we want to access, say, the first two elements:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">codes[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]
<span class="co">#&gt;  italy canada </span>
<span class="co">#&gt;    380    124</span></code></pre></div>
<p>If the elements have names, we can also access the entries using these names. Below are two examples.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">codes[<span class="st">&quot;canada&quot;</span>]
<span class="co">#&gt; canada </span>
<span class="co">#&gt;    124</span>
codes[<span class="kw">c</span>(<span class="st">&quot;egypt&quot;</span>,<span class="st">&quot;italy&quot;</span>)]
<span class="co">#&gt; egypt italy </span>
<span class="co">#&gt;   818   380</span></code></pre></div>
</div>
<div id="coercion" class="section level3">
<h3><span class="header-section-number">1.7.5</span> Coercion</h3>
<p>In general, <em>coercion</em> is an attempt by R to be flexible with data types. When an entry does not match the expected, some of the prebuilt R functions try to guess what was meant before throwing an error. This can also lead to confusion. Failing to understand <em>coercion</em> can drive programmers crazy when attempting to code in R since it behaves quite differently from most other languages in this regard. Let’s learn about it with some examples.</p>
<p>We said that vectors must be all of the same type. So if we try to combine, say, numbers and characters, you might expect an error:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="st">&quot;canada&quot;</span>, <span class="dv">3</span>)</code></pre></div>
<p>But we don’t get one, not even a warning! What happened? Look at <code>x</code> and its class:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x
<span class="co">#&gt; [1] &quot;1&quot;      &quot;canada&quot; &quot;3&quot;</span>
<span class="kw">class</span>(x)
<span class="co">#&gt; [1] &quot;character&quot;</span></code></pre></div>
<p>R <em>coerced</em> the data into characters. It guessed that because you put a character string in the vector, you meant the 1 and 3 to actually be character strings <code>&quot;1&quot;</code> and “<code>3</code>”. The fact that not even a warning is issued is an example of how coercion can cause many unnoticed errors in R.</p>
<p>R also offers functions to change from one type to another. For example, you can turn numbers into characters with:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">5</span>
y &lt;-<span class="st"> </span><span class="kw">as.character</span>(x)
y
<span class="co">#&gt; [1] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; &quot;5&quot;</span></code></pre></div>
<p>And you can turn it back with <code>as.numeric</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.numeric</span>(y)
<span class="co">#&gt; [1] 1 2 3 4 5</span></code></pre></div>
<p>This function is actually quite useful since datasets that include numbers as character strings are common.</p>
</div>
<div id="not-availables-na" class="section level3">
<h3><span class="header-section-number">1.7.6</span> Not Availables (NA)</h3>
<p>When a function tries to coerce on type to another and encounters an impossible case, it usually gives us a warning and turns the entry into a special value called an <code>NA</code> for “not available”. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;1&quot;</span>, <span class="st">&quot;b&quot;</span>, <span class="st">&quot;3&quot;</span>)
<span class="kw">as.numeric</span>(x)
<span class="co">#&gt; Warning: NAs introduced by coercion</span>
<span class="co">#&gt; [1]  1 NA  3</span></code></pre></div>
<p>R does not have any guesses for what number you want when you type <code>b</code> so it does not try.</p>
<p>As a data scientist you will encounter the <code>NA</code> often as they are generally used for missing data, a common problem in real life datasets.</p>
</div>
<div id="exercises-2" class="section level3 unnumbered">
<h3>Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Use the function <code>c</code> to create a vector with the average high temperatures in January for Beijing, Lagos, Paris, Rio de Janeiro, San Juan, and Toronto, which are 35, 88, 42, 84, 81, and 30 degrees Fahrenheit. Call the object <code>temp</code>.</p></li>
<li><p>Now create a vector with the city names and call the object <code>city</code>.</p></li>
<li><p>Use the <code>names</code> function and the objects defined in the previous exercises to associate the temperature data with its corresponding city.</p></li>
<li><p>Use the <code>[</code> and <code>:</code> operators to access the temperature of the first three cities on the list.</p></li>
<li><p>Use the <code>[</code> operator to access the temperature of Paris and San Juan.</p></li>
<li><p>Use the <code>:</code> operator to create a sequence of numbers <span class="math inline">\(12,13,14,\dots,73\)</span>.</p></li>
<li><p>Create a vector containing all the positive odd numbers smaller than 100.</p></li>
<li><p>Create a vector of numbers that starts at 6, does not pass 55, and adds numbers in increments of 4/7: 6, 6+4/7, 6+8/7, etc.. How many numbers does the list have? Hint: use <code>seq</code> and <code>length</code>.</p></li>
<li><p>What is the class of the following object <code>a &lt;- seq(1, 10, 0.5)</code>?</p></li>
<li><p>What is the class of the following object <code>a &lt;- seq(1, 10)</code>?</p></li>
<li><p>The class of <code>class(a&lt;-1)</code> is numeric not integer. R defaults to numeric and, to force a number, you need to add the letter <code>L</code>. Confirm that the class of <code>1L</code> is integer.</p></li>
<li><p>Define the following vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;1&quot;</span>, <span class="st">&quot;3&quot;</span>, <span class="st">&quot;5&quot;</span>)</code></pre></div>
<p>and coerce it to get integers.</p></li>
</ol>

</div>
</div>
<div id="sorting" class="section level2">
<h2><span class="header-section-number">1.8</span> Sorting</h2>
<p>Now that we have mastered some basic R knowledge, let’s try to gain some insights into the safety of different states in the context of gun murders.</p>
<div id="sort" class="section level3">
<h3><span class="header-section-number">1.8.1</span> <code>sort</code></h3>
<p>Say we want to rank the states from least to most gun murders. The function <code>sort</code> sorts a vector in increasing order. We can therefore see the largest number of gun murders by typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dslabs)
<span class="kw">data</span>(murders)
<span class="kw">sort</span>(murders<span class="op">$</span>total)
<span class="co">#&gt;  [1]    2    4    5    5    7    8   11   12   12   16   19   21   22   27</span>
<span class="co">#&gt; [15]   32   36   38   53   63   65   67   84   93   93   97   97   99  111</span>
<span class="co">#&gt; [29]  116  118  120  135  142  207  219  232  246  250  286  293  310  321</span>
<span class="co">#&gt; [43]  351  364  376  413  457  517  669  805 1257</span></code></pre></div>
<p>However, this does not give us information about which states have which murder totals. For example, we don’t know which state had 1257 murders in 2010.</p>
</div>
<div id="order" class="section level3">
<h3><span class="header-section-number">1.8.2</span> <code>order</code></h3>
<p>The function <code>order</code> is closer to what we want. It takes a vector as input and returns the vector of indexes that sorts the input vector. This may sound confusing so let’s look at a simple example. We can create a vector and sort it:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">31</span>, <span class="dv">4</span>, <span class="dv">15</span>, <span class="dv">92</span>, <span class="dv">65</span>)
<span class="kw">sort</span>(x)
<span class="co">#&gt; [1]  4 15 31 65 92</span></code></pre></div>
<p>Rather than sort the input vector, the function <code>order</code> returns the index that sorts input vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">index &lt;-<span class="st"> </span><span class="kw">order</span>(x)
x[index]
<span class="co">#&gt; [1]  4 15 31 65 92</span></code></pre></div>
<p>This is the same output as that returned by <code>sort(x)</code>. If we look at this index, we see why it works:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x
<span class="co">#&gt; [1] 31  4 15 92 65</span>
<span class="kw">order</span>(x)
<span class="co">#&gt; [1] 2 3 1 5 4</span></code></pre></div>
<p>The second and fourth entry of <code>x</code> are the smallest, so <code>order(x)</code> starts with <code>2</code>. The next smallest is the third entry, so the second entry is <code>3</code> and so on.</p>
<p>How does this help us order the states by murders? First remember that the entries of vectors you access with <code>$</code> follow the same order as the rows in the table. So, for example, these two vectors, containing the state names and abbreviations respectively, are matched by their order:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders<span class="op">$</span>state[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>]
<span class="co">#&gt;  [1] &quot;Alabama&quot;              &quot;Alaska&quot;               &quot;Arizona&quot;             </span>
<span class="co">#&gt;  [4] &quot;Arkansas&quot;             &quot;California&quot;           &quot;Colorado&quot;            </span>
<span class="co">#&gt;  [7] &quot;Connecticut&quot;          &quot;Delaware&quot;             &quot;District of Columbia&quot;</span>
<span class="co">#&gt; [10] &quot;Florida&quot;</span>
murders<span class="op">$</span>abb[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>]
<span class="co">#&gt;  [1] &quot;AL&quot; &quot;AK&quot; &quot;AZ&quot; &quot;AR&quot; &quot;CA&quot; &quot;CO&quot; &quot;CT&quot; &quot;DE&quot; &quot;DC&quot; &quot;FL&quot;</span></code></pre></div>
<p>This means we can now order the state names by their total murders by first obtaining the index that orders the vectors according to murder totals, and then indexing the state names or abbreviation vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind &lt;-<span class="st"> </span><span class="kw">order</span>(murders<span class="op">$</span>total) 
murders<span class="op">$</span>abb[ind] 
<span class="co">#&gt;  [1] &quot;VT&quot; &quot;ND&quot; &quot;NH&quot; &quot;WY&quot; &quot;HI&quot; &quot;SD&quot; &quot;ME&quot; &quot;ID&quot; &quot;MT&quot; &quot;RI&quot; &quot;AK&quot; &quot;IA&quot; &quot;UT&quot; &quot;WV&quot;</span>
<span class="co">#&gt; [15] &quot;NE&quot; &quot;OR&quot; &quot;DE&quot; &quot;MN&quot; &quot;KS&quot; &quot;CO&quot; &quot;NM&quot; &quot;NV&quot; &quot;AR&quot; &quot;WA&quot; &quot;CT&quot; &quot;WI&quot; &quot;DC&quot; &quot;OK&quot;</span>
<span class="co">#&gt; [29] &quot;KY&quot; &quot;MA&quot; &quot;MS&quot; &quot;AL&quot; &quot;IN&quot; &quot;SC&quot; &quot;TN&quot; &quot;AZ&quot; &quot;NJ&quot; &quot;VA&quot; &quot;NC&quot; &quot;MD&quot; &quot;OH&quot; &quot;MO&quot;</span>
<span class="co">#&gt; [43] &quot;LA&quot; &quot;IL&quot; &quot;GA&quot; &quot;MI&quot; &quot;PA&quot; &quot;NY&quot; &quot;FL&quot; &quot;TX&quot; &quot;CA&quot;</span></code></pre></div>
<p>According to the above, California had the most murders.</p>
</div>
<div id="max-and-which.max" class="section level3">
<h3><span class="header-section-number">1.8.3</span> <code>max</code> and <code>which.max</code></h3>
<p>If we are only interested in the entry with the largest value we can use <code>max</code> for the value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">max</span>(murders<span class="op">$</span>total)
<span class="co">#&gt; [1] 1257</span></code></pre></div>
<p>and <code>which.max</code> for the index of the largest value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">i_max &lt;-<span class="st"> </span><span class="kw">which.max</span>(murders<span class="op">$</span>total)
murders<span class="op">$</span>state[i_max]
<span class="co">#&gt; [1] &quot;California&quot;</span></code></pre></div>
<p>For the minimum we can use <code>min</code> and <code>which.min</code> in the same way.</p>
<p>So is California the most dangerous state? In an upccoming section we argue that we should be considering rates not totals. Before doing that we introduce one last order related function: <code>rank</code></p>
</div>
<div id="rank" class="section level3">
<h3><span class="header-section-number">1.8.4</span> <code>rank</code></h3>
<p>Although not as frequently used as <code>order</code> and <code>sort</code>, the function <code>rank</code> is also related to order and can be useful. For any given vector it returns a vector with the rank of the first entry, second entry, etc., of the input vector. Here is a simple example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">31</span>, <span class="dv">4</span>, <span class="dv">15</span>, <span class="dv">92</span>, <span class="dv">65</span>)
<span class="kw">rank</span>(x)
<span class="co">#&gt; [1] 3 1 2 5 4</span></code></pre></div>
<p>To summarize let’s look at the results of the three functions we have introduced:</p>
<table>
<thead>
<tr class="header">
<th align="right">original</th>
<th align="right">sort</th>
<th align="right">order</th>
<th align="right">rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">31</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">15</td>
<td align="right">3</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="right">31</td>
<td align="right">1</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">92</td>
<td align="right">65</td>
<td align="right">5</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="right">65</td>
<td align="right">92</td>
<td align="right">4</td>
<td align="right">4</td>
</tr>
</tbody>
</table>
</div>
<div id="beware-of-recycling" class="section level3">
<h3><span class="header-section-number">1.8.5</span> Beware of recycling</h3>
<p>Another common source of unnoticed errors in R is the use of <em>recycling</em>. We saw that vectors are added elementwise. So if the vectors don’t match in length it is natural to assume that we should get an error. But we don’t. Notice what happens:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>, <span class="dv">70</span>)
x<span class="op">+</span>y
<span class="co">#&gt; Warning in x + y: longer object length is not a multiple of shorter object</span>
<span class="co">#&gt; length</span>
<span class="co">#&gt; [1] 11 22 33 41 52 63 71</span></code></pre></div>
<p>We do get a warning but no error. For the output, R has recycled the numbers in <code>x</code>: notice the last digit of numbers in the output.</p>
</div>
<div id="exercise" class="section level3 unnumbered">
<h3>Exercise</h3>
<p>For these exercises we will use the US murders dataset. Make sure you load it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dslabs)
<span class="kw">data</span>(murders)</code></pre></div>
<ol style="list-style-type: decimal">
<li><p>Use the <code>$</code> operator to access the population size data and store it the object <code>pop</code>. Then use the <code>sort</code> function to redefine <code>pop</code> so that it is sorted. Finally use the <code>[</code> operator to report the smallest population size.</p></li>
<li><p>Now instead of the smallest population size, find the index of the entry with the smallest population size. Hint: use <code>order</code> instead of <code>sort</code>.</p></li>
<li><p>We can actually perform the same operation as in the previous exercise using the function <code>which.min</code>. Write one line of code that does this.</p></li>
<li><p>Now we know how small the smallest state is and we know which row represents it. However, which state is it? Define a variable <code>states</code> to be the state names from the <code>murders</code> data frame. Report the name of the state with the smallest population.</p></li>
<li><p>You can create a data frame using the <code>data.frame</code> function. Here is a quick example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">35</span>, <span class="dv">88</span>, <span class="dv">42</span>, <span class="dv">84</span>, <span class="dv">81</span>, <span class="dv">30</span>)
city &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Beijing&quot;</span>, <span class="st">&quot;Lagos&quot;</span>, <span class="st">&quot;Paris&quot;</span>, <span class="st">&quot;Rio de Janeiro&quot;</span>, <span class="st">&quot;San Juan&quot;</span>, <span class="st">&quot;Toronto&quot;</span>)
city_temps &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">name =</span> city, <span class="dt">temperature =</span> temp)</code></pre></div>
<p>Use the <code>rank</code> function to determine the population size rank (from smallest to biggest) of each state. Save these ranks in an object called <code>ranks</code>, then create a data frame with the state name and its rank. Call the data frame <code>my_df</code>.</p></li>
<li><p>Repeat the previous exercise but this time order <code>my_df</code> so that the states are ordered from least populous to most populous. Hint: create an object <code>ind</code> that stores the indexes needed to order the population values. Then use the bracket operator <code>[</code> to re-order each column in the data frame.</p></li>
<li><p>The <code>na_example</code> represents a series of counts. You can quickly examine the object using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(na_example)  
<span class="kw">str</span>(na_example)
<span class="co">#&gt;  int [1:1000] 2 1 3 2 1 3 1 4 3 2 ...</span></code></pre></div>
<p>However, when we compute the average we obtain an <code>NA</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(na_example)
<span class="co">#&gt; [1] NA</span></code></pre></div>
<p>The <code>is.na</code> returns a logical vector that tells us which entries are <code>NA</code>. Assign this logical vector to an object called <code>ind</code> and determine how many <code>NA</code>s does <code>na_example</code> have.</p></li>
<li><p>Now compute the average again, but only for the entries that are not <code>NA</code>. Hint: remember the <code>!</code> operator.</p></li>
</ol>

</div>
</div>
<div id="vector-arithmetics" class="section level2">
<h2><span class="header-section-number">1.9</span> Vector arithmetics</h2>
<p>California had the most murders, but does this mean it is the most dangerous state? What if it just has many more people than any other state? We can very quickly confirm that, indeed, California has the largest population:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders<span class="op">$</span>state[<span class="kw">which.max</span>(murders<span class="op">$</span>population)]
<span class="co">#&gt; [1] &quot;California&quot;</span></code></pre></div>
<p>with over 37 million inhabitants. It is therefore unfair to compare the totals if we are interested in learning how safe the state is.</p>
<p>What we really should be computing is the murders per capita. The reports we describe in the motivating section used murders per 100,000 as the unit. To compute this quantity, the powerful vector arithmetic capabilities of R come in handy.</p>
<div id="rescaling" class="section level3">
<h3><span class="header-section-number">1.9.1</span> Rescaling</h3>
<p>In R, arithmetic operations on vectors occur <em>element wise</em>. For a quick example suppose we have height in inches:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">heights &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">69</span>, <span class="dv">62</span>, <span class="dv">66</span>, <span class="dv">70</span>, <span class="dv">70</span>, <span class="dv">73</span>, <span class="dv">67</span>, <span class="dv">73</span>, <span class="dv">67</span>, <span class="dv">70</span>)</code></pre></div>
<p>and want to covert to centimeters. Notice what happens when we multiply <code>heights</code> by 2.54:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">heights <span class="op">*</span><span class="st"> </span><span class="fl">2.54</span>
<span class="co">#&gt;  [1] 175 157 168 178 178 185 170 185 170 178</span></code></pre></div>
<p>It multiplied each element by 2.54. Similarly, if we want to compute how many inches taller or shorter than 69 inches, the average height for males, we can subtract it from every entry like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">heights <span class="op">-</span><span class="st"> </span><span class="dv">69</span>
<span class="co">#&gt;  [1]  0 -7 -3  1  1  4 -2  4 -2  1</span></code></pre></div>
</div>
<div id="two-vectors" class="section level3">
<h3><span class="header-section-number">1.9.2</span> Two vectors</h3>
<p>If we have two vectors of the same length, and we sum them in R, they will be added entry by entry as follows:</p>
<p><span class="math display">\[
\begin{pmatrix}
a\\
b\\
c\\
d
\end{pmatrix}
+
\begin{pmatrix}
e\\
f\\
g\\
h
\end{pmatrix}
=
\begin{pmatrix}
a +e\\
b + f\\
c + g\\
d + h
\end{pmatrix}
\]</span></p>
<p>The same holds for other mathematical operations, such as <code>-</code>, <code>*</code> and <code>/</code>.</p>
<p>This implies that to compute the murder rates we can simply type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murder_rate &lt;-<span class="st"> </span>murders<span class="op">$</span>total <span class="op">/</span><span class="st"> </span>murders<span class="op">$</span>population <span class="op">*</span><span class="st"> </span><span class="dv">100000</span></code></pre></div>
<p>Once we do this, we notice that California is no longer near the top of the list. In fact, we can use what we have learned to order the states by murder rate:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders<span class="op">$</span>state[<span class="kw">order</span>(murder_rate)]
<span class="co">#&gt;  [1] &quot;Vermont&quot;              &quot;New Hampshire&quot;        &quot;Hawaii&quot;              </span>
<span class="co">#&gt;  [4] &quot;North Dakota&quot;         &quot;Iowa&quot;                 &quot;Idaho&quot;               </span>
<span class="co">#&gt;  [7] &quot;Utah&quot;                 &quot;Maine&quot;                &quot;Wyoming&quot;             </span>
<span class="co">#&gt; [10] &quot;Oregon&quot;               &quot;South Dakota&quot;         &quot;Minnesota&quot;           </span>
<span class="co">#&gt; [13] &quot;Montana&quot;              &quot;Colorado&quot;             &quot;Washington&quot;          </span>
<span class="co">#&gt; [16] &quot;West Virginia&quot;        &quot;Rhode Island&quot;         &quot;Wisconsin&quot;           </span>
<span class="co">#&gt; [19] &quot;Nebraska&quot;             &quot;Massachusetts&quot;        &quot;Indiana&quot;             </span>
<span class="co">#&gt; [22] &quot;Kansas&quot;               &quot;New York&quot;             &quot;Kentucky&quot;            </span>
<span class="co">#&gt; [25] &quot;Alaska&quot;               &quot;Ohio&quot;                 &quot;Connecticut&quot;         </span>
<span class="co">#&gt; [28] &quot;New Jersey&quot;           &quot;Alabama&quot;              &quot;Illinois&quot;            </span>
<span class="co">#&gt; [31] &quot;Oklahoma&quot;             &quot;North Carolina&quot;       &quot;Nevada&quot;              </span>
<span class="co">#&gt; [34] &quot;Virginia&quot;             &quot;Arkansas&quot;             &quot;Texas&quot;               </span>
<span class="co">#&gt; [37] &quot;New Mexico&quot;           &quot;California&quot;           &quot;Florida&quot;             </span>
<span class="co">#&gt; [40] &quot;Tennessee&quot;            &quot;Pennsylvania&quot;         &quot;Arizona&quot;             </span>
<span class="co">#&gt; [43] &quot;Georgia&quot;              &quot;Mississippi&quot;          &quot;Michigan&quot;            </span>
<span class="co">#&gt; [46] &quot;Delaware&quot;             &quot;South Carolina&quot;       &quot;Maryland&quot;            </span>
<span class="co">#&gt; [49] &quot;Missouri&quot;             &quot;Louisiana&quot;            &quot;District of Columbia&quot;</span></code></pre></div>
</div>
<div id="exercises-3" class="section level3 unnumbered">
<h3>Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Previously we created this data frame:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">35</span>, <span class="dv">88</span>, <span class="dv">42</span>, <span class="dv">84</span>, <span class="dv">81</span>, <span class="dv">30</span>)
city &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Beijing&quot;</span>, <span class="st">&quot;Lagos&quot;</span>, <span class="st">&quot;Paris&quot;</span>, <span class="st">&quot;Rio de Janeiro&quot;</span>, <span class="st">&quot;San Juan&quot;</span>, <span class="st">&quot;Toronto&quot;</span>)
city_temps &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">name =</span> city, <span class="dt">temperature =</span> temp)</code></pre></div>
<p>Remake the data frame using the code above, but add a line that converts the temperature from Fahrenheit to Celsius.</p></li>
<li><p>What is the following sum <span class="math inline">\(1+1/2^2 + 1/3^2 + \dots 1/100^2\)</span>? Hint: thanks to Euler we know it should be close to <span class="math inline">\(\pi^2/6\)</span>.</p></li>
<li><p>Compute the per 100,000 murder rate for each state and store it in the object <code>murder_rate</code>. Then compute the average murder rate for the US using the function <code>mean</code>. What is the average?</p></li>
</ol>

</div>
</div>
<div id="indexing" class="section level2">
<h2><span class="header-section-number">1.10</span> Indexing</h2>
<p>R provides a powerful and convenient way of indexing vectors. We can, for example, subset a vector based on properties of another vector. We continue our US murders example to demonstrate:</p>
<div id="subsetting-with-logicals" class="section level3">
<h3><span class="header-section-number">1.10.1</span> Subsetting with logicals</h3>
<p>We have now calculated the murder rate using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murder_rate &lt;-<span class="st"> </span>murders<span class="op">$</span>total <span class="op">/</span><span class="st"> </span>murders<span class="op">$</span>population <span class="op">*</span><span class="st"> </span><span class="dv">100000</span> </code></pre></div>
<p>Imagine you are moving from Italy where, according to the ABC news report, the murder rate is only 0.71 per 100,000. You would prefer to move to a state with a similar murder rate. Another powerful feature of R is that we can we can use logicals to index vectors. If we compare a vector to a single number, it actually performs the test for each entry. The following is an example related to the question above:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind &lt;-<span class="st"> </span>murder_rate <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.71</span></code></pre></div>
<p>Or if we want to know if its less or equal we can use:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind &lt;-<span class="st"> </span>murder_rate <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.71</span>
ind
<span class="co">#&gt;  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</span>
<span class="co">#&gt; [12]  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE</span>
<span class="co">#&gt; [23] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE</span>
<span class="co">#&gt; [34] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</span>
<span class="co">#&gt; [45] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE</span></code></pre></div>
<p>Note that we get back a logical vector with <code>TRUE</code> for each entry smaller than or equal to 0.71. To see which states these are, we can leverage the fact that vectors can be indexed with logicals.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders<span class="op">$</span>state[ind]
<span class="co">#&gt; [1] &quot;Hawaii&quot;        &quot;Iowa&quot;          &quot;New Hampshire&quot; &quot;North Dakota&quot; </span>
<span class="co">#&gt; [5] &quot;Vermont&quot;</span></code></pre></div>
<p>In order to count how many are TRUE, the function <code>sum</code> returns the sum of the entries of a vector and logical vectors get <em>coerced</em> to numeric with <code>TRUE</code> coded as 1 and <code>FALSE</code> as 0. Thus we can count the states using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(ind)
<span class="co">#&gt; [1] 5</span></code></pre></div>
</div>
<div id="logical-operators" class="section level3">
<h3><span class="header-section-number">1.10.2</span> Logical operators</h3>
<p>Suppose we like the mountains and we want to move to a safe state in the western region of the country. We want the murder rate to be at most 1. So we want two different things to be true. Here we can use the logical operator <em>and</em>, which in R is represented with <code>&amp;</code>. This operation results in <code>TRUE</code>, only when both logicals are <code>TRUE</code>. To see this consider this example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="ot">TRUE</span> <span class="op">&amp;</span><span class="st"> </span><span class="ot">TRUE</span>
<span class="co">#&gt; [1] TRUE</span>
<span class="ot">TRUE</span> <span class="op">&amp;</span><span class="st"> </span><span class="ot">FALSE</span>
<span class="co">#&gt; [1] FALSE</span>
<span class="ot">FALSE</span> <span class="op">&amp;</span><span class="st"> </span><span class="ot">FALSE</span>
<span class="co">#&gt; [1] FALSE</span></code></pre></div>
<p>For our exmaple, we can form two logicals:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">west &lt;-<span class="st"> </span>murders<span class="op">$</span>region <span class="op">==</span><span class="st"> &quot;West&quot;</span>
safe &lt;-<span class="st"> </span>murder_rate <span class="op">&lt;=</span><span class="st"> </span><span class="dv">1</span></code></pre></div>
<p>and we can use the <code>&amp;</code> to get a vector of logicals that tells us which states satisfy both conditions:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind &lt;-<span class="st"> </span>safe <span class="op">&amp;</span><span class="st"> </span>west
murders<span class="op">$</span>state[ind]
<span class="co">#&gt; [1] &quot;Hawaii&quot;  &quot;Idaho&quot;   &quot;Oregon&quot;  &quot;Utah&quot;    &quot;Wyoming&quot;</span></code></pre></div>
</div>
<div id="which" class="section level3">
<h3><span class="header-section-number">1.10.3</span> <code>which</code></h3>
<p>Suppose we want to look up California’s murder rate. For this type of operation, it is convenient to convert vectors of logicals into indexes instead of keeping long vectors of logicals. The function <code>which</code> tells us which entries of a logical vector are TRUE. So we can type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind &lt;-<span class="st"> </span><span class="kw">which</span>(murders<span class="op">$</span>state <span class="op">==</span><span class="st"> &quot;California&quot;</span>)
ind ##this is the index that matches the California entry
<span class="co">#&gt; [1] 5</span>
murder_rate[ind]
<span class="co">#&gt; [1] 3.37</span></code></pre></div>
</div>
<div id="match" class="section level3">
<h3><span class="header-section-number">1.10.4</span> <code>match</code></h3>
<p>If instead of just one state we want to find out the murder rates for several, say New York, Florida, and Texas, we can use the function <code>match</code>. This function tells us which indexes of a second vector match each of the entries of a first vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind &lt;-<span class="st"> </span><span class="kw">match</span>(<span class="kw">c</span>(<span class="st">&quot;New York&quot;</span>, <span class="st">&quot;Florida&quot;</span>, <span class="st">&quot;Texas&quot;</span>), murders<span class="op">$</span>state)
ind
<span class="co">#&gt; [1] 33 10 44</span></code></pre></div>
<p>Now we can look at the murder rates:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murder_rate[ind]
<span class="co">#&gt; [1] 2.67 3.40 3.20</span></code></pre></div>
</div>
<div id="in" class="section level3">
<h3><span class="header-section-number">1.10.5</span> <code>%in%</code></h3>
<p>If rather than an index we want a logical that tells us whether or not each element of a first vector is in a second, we can use the function <code>%in%</code>. So, say you are not sure if Boston, Dakota and Washington are states, you can find out like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(<span class="st">&quot;Boston&quot;</span>, <span class="st">&quot;Dakota&quot;</span>, <span class="st">&quot;Washington&quot;</span>) <span class="op">%in%</span><span class="st"> </span>murders<span class="op">$</span>state
<span class="co">#&gt; [1] FALSE FALSE  TRUE</span></code></pre></div>
<p>We will be using <code>%in%</code> often throughout the book.</p>
<p><strong>Advanced</strong>: There is a connection between <code>match</code> and <code>%in%</code> through <code>which</code>. To see this, notice that the following two lines of code are equivalent:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">match</span>(<span class="kw">c</span>(<span class="st">&quot;New York&quot;</span>, <span class="st">&quot;Florida&quot;</span>, <span class="st">&quot;Texas&quot;</span>), murders<span class="op">$</span>state)
<span class="co">#&gt; [1] 33 10 44</span>
<span class="kw">which</span>(murders<span class="op">$</span>state<span class="op">%in%</span><span class="kw">c</span>(<span class="st">&quot;New York&quot;</span>, <span class="st">&quot;Florida&quot;</span>, <span class="st">&quot;Texas&quot;</span>))
<span class="co">#&gt; [1] 10 33 44</span></code></pre></div>
</div>
<div id="exercises-4" class="section level3 unnumbered">
<h3>Exercises</h3>
<p>Start by loading the library and data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dslabs)
<span class="kw">data</span>(murders)</code></pre></div>
<ol style="list-style-type: decimal">
<li><p>Compute the per 100,000 murder rate for each state and store it in an object called <code>murder_rate</code>. Then use the logical operators to create a logical vector, name it <code>low</code>; that tells us which entries of <code>murder_rate</code> are lower than</p></li>
<li><p>Now use the results from the previous exercise and the function <code>which</code> to determine the indices of <code>murder_rate</code> associated with values lower than 1.</p></li>
<li><p>Use the results from the previous exercise to report the names of the states with murder rates lower than 1.</p></li>
<li><p>Now extend the code from exercise 2 and 3 to report the states in the Northeast with murder rates lower than 1. Hint: use the previously defined logical vector <code>low</code> and the logical operator <code>&amp;</code>.</p></li>
<li><p>In a previous exercise we computed the murder rate for each rate and the average of these numbers. How many states are below the average?</p></li>
<li><p>Use the match function to identify the states with abbreviations AK, MI, and IA. Hint: start by defining an index of the entries of <code>murders$abb</code> that match the three abbreviations, then use the <code>[</code> operator to extract the states.</p></li>
<li><p>Use the <code>%in%</code> operator to create a logical vector that answers the question: which of the following are actual abbreviations: MA, ME, MI, MO, MU ?</p></li>
<li><p>Extend the code you used in exercise 7 to report the one entry that is <strong>not</strong> an actual abbreviation. Hint: use the <code>!</code> operator, which turns <code>FALSE</code> into <code>TRUE</code> and vice versa, then <code>which</code> to obtain an index.</p></li>
</ol>

</div>
</div>
<div id="basic-data-wrangling" class="section level2">
<h2><span class="header-section-number">1.11</span> Basic Data Wrangling</h2>
<p>Up to now we have been changing vectors by reordering them and subsetting them through indexing. However, once we start more advanced analyses, we will want to prepare data tables for data analysis. We refer to this task as data wrangling. For this purpose we will introduce the <code>dplyr</code> package which provides intuitive functionality for working with tables. In Chapter 6 we will cover the <code>dplyr</code> package in much more depth.</p>
<p>Once you install <code>dplyr</code> you can load it using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)</code></pre></div>
<p>This package introduces functions that perform the most common operations in data wrangling and uses names for these functions that are relatively easy to remember. For example, to change the data table by adding a new column, we use <code>mutate</code>. To filter the data table to a subset of rows, we use <code>filter</code>. Finally, to subset the data by selecting specific columns, we use <code>select</code>. We can also perform a series of operations, for example select and then filter, by sending the results of one function to another using what is called the <em>pipe operator</em>: <code>%&gt;%</code>. Some details are included below.</p>
<div id="adding-a-column-with-mutate" class="section level3">
<h3><span class="header-section-number">1.11.1</span> Adding a column with <code>mutate</code></h3>
<p>We want all the necessary information for our analysis to be included in the data table. So the first task is to add the murder rates to our data frame. The function mutate takes the data frame as a first argument and the name and values of the variable in the second using the convention <code>name = values</code>. So to add murder rates we use:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders &lt;-<span class="st"> </span><span class="kw">mutate</span>(murders, <span class="dt">rate =</span> total <span class="op">/</span><span class="st"> </span>population <span class="op">*</span><span class="st"> </span><span class="dv">100000</span>)</code></pre></div>
<p>Note that here we used <code>total</code> and <code>population</code> inside the function, which are objects that are <strong>not</strong> defined in our workspace. So why do we not get an error?</p>
<p>This is one of the main features of dplyr. Function in this package, such <code>mutate</code>, know to look for variables in the data frame provided in the first argument. So in the call to mutate above, <code>total</code> will have the values in <code>murders$total</code>. This approach makes the code much more redable.</p>
<p>We can see the new column is added:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(murders)
<span class="co">#&gt;        state abb region population total rate</span>
<span class="co">#&gt; 1    Alabama  AL  South    4779736   135 2.82</span>
<span class="co">#&gt; 2     Alaska  AK   West     710231    19 2.68</span>
<span class="co">#&gt; 3    Arizona  AZ   West    6392017   232 3.63</span>
<span class="co">#&gt; 4   Arkansas  AR  South    2915918    93 3.19</span>
<span class="co">#&gt; 5 California  CA   West   37253956  1257 3.37</span>
<span class="co">#&gt; 6   Colorado  CO   West    5029196    65 1.29</span></code></pre></div>
<p>Note: Although we have over-written the original <code>murders</code> object, this does not change the object that loaded with <code>data(murders)</code>. If we load the <code>murders</code> data again, the original will over-write our mutated version.</p>
</div>
<div id="subsetting-with-filter" class="section level3">
<h3><span class="header-section-number">1.11.2</span> Subsetting with <code>filter</code></h3>
<p>Now suppose that we want to filter the data table to only show the entries for which the murder rate is lower than 0.71. To do this we use the <code>filter</code> function which takes the data table as an argument and then the conditional statement as the next. Like mutate, we can use the unquoted variable names from <code>murders</code> inside the function and it will know we mean the columns and not objects in the workspace.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(murders, rate <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.71</span>)
<span class="co">#&gt;           state abb        region population total  rate</span>
<span class="co">#&gt; 1        Hawaii  HI          West    1360301     7 0.515</span>
<span class="co">#&gt; 2          Iowa  IA North Central    3046355    21 0.689</span>
<span class="co">#&gt; 3 New Hampshire  NH     Northeast    1316470     5 0.380</span>
<span class="co">#&gt; 4  North Dakota  ND North Central     672591     4 0.595</span>
<span class="co">#&gt; 5       Vermont  VT     Northeast     625741     2 0.320</span></code></pre></div>
</div>
<div id="selecting-columns-with-select" class="section level3">
<h3><span class="header-section-number">1.11.3</span> Selecting columns with <code>select</code></h3>
<p>Although our data table only has six columns, some data tables include hundreds. If we want to view just a few, we can use the dplyr <code>select</code> function. In the code below we select three columns, assign this to a new object and then filter the new object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">new_table &lt;-<span class="st"> </span><span class="kw">select</span>(murders, state, region, rate)
<span class="kw">filter</span>(new_table, rate <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.71</span>)
<span class="co">#&gt;           state        region  rate</span>
<span class="co">#&gt; 1        Hawaii          West 0.515</span>
<span class="co">#&gt; 2          Iowa North Central 0.689</span>
<span class="co">#&gt; 3 New Hampshire     Northeast 0.380</span>
<span class="co">#&gt; 4  North Dakota North Central 0.595</span>
<span class="co">#&gt; 5       Vermont     Northeast 0.320</span></code></pre></div>
<p>In the call to <code>select</code>, the first argument, <code>murders</code>, is an object but <code>state</code>, <code>region</code>, and <code>rate</code> are variable names.</p>
</div>
<div id="the-pipe" class="section level3">
<h3><span class="header-section-number">1.11.4</span> The pipe: <code>%&gt;%</code></h3>
<p>We wrote the code above because we wanted to show the three variables for states that have murder rates below 0.71. To do this we defined the intermediate object <code>new_table</code>. In <code>dplyr</code> we can write code that looks more like a description of what we want to do:</p>
<p><span class="math display">\[ \mbox{original data }
\rightarrow \mbox{ select }
\rightarrow \mbox{ filter } \]</span></p>
<p>For such an operation, we can use the pipe <code>%&gt;%</code>. The code looks like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(state, region, rate) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(rate <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.71</span>)
<span class="co">#&gt;           state        region  rate</span>
<span class="co">#&gt; 1        Hawaii          West 0.515</span>
<span class="co">#&gt; 2          Iowa North Central 0.689</span>
<span class="co">#&gt; 3 New Hampshire     Northeast 0.380</span>
<span class="co">#&gt; 4  North Dakota North Central 0.595</span>
<span class="co">#&gt; 5       Vermont     Northeast 0.320</span></code></pre></div>
<p>This line of code is equivalent to the two lines of code above. What is going on here?</p>
<p>In general, the pipe <em>sends</em> the result of the left side of the pipe to be the first argument of the function on the right side of the pipe. Here is a very simple example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">16</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sqrt</span>()
<span class="co">#&gt; [1] 4</span></code></pre></div>
<p>We can continue to pipe values along:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">16</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sqrt</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">log2</span>()
<span class="co">#&gt; [1] 2</span></code></pre></div>
<p>The above statement is equivalent to <code>log2(sqrt(16))</code></p>
<p>Remember that the pipe sends values to the first argument so we can define arguments as if the first argument is already defined:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">16</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sqrt</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">log</span>(<span class="dt">base =</span> <span class="dv">2</span>)
<span class="co">#&gt; [1] 2</span></code></pre></div>
<p>So when using the pipe with data frames and <code>dplyr</code> we no longer need to specify the required first argument since the <code>dplyr</code> functions we have described all take the data as the first argument. So in the code we wrote:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(state, region, rate) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(rate <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.71</span>)</code></pre></div>
<p><code>murders</code> is the first argument of the <code>select</code> function and the new data frame, formerly <code>new_table</code>, is the first argument of the <code>filter</code> function.</p>
</div>
<div id="creating-a-data-frame" class="section level3">
<h3><span class="header-section-number">1.11.5</span> Creating a data frame</h3>
<p>It is sometimes useful for us to create our own data frames. You can do this by using the <code>data.frame</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">grades &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">names =</span> <span class="kw">c</span>(<span class="st">&quot;John&quot;</span>, <span class="st">&quot;Juan&quot;</span>, <span class="st">&quot;Jean&quot;</span>, <span class="st">&quot;Yao&quot;</span>), 
                     <span class="dt">exam_1 =</span> <span class="kw">c</span>(<span class="dv">95</span>, <span class="dv">80</span>, <span class="dv">90</span>, <span class="dv">85</span>), 
                     <span class="dt">exam_2 =</span> <span class="kw">c</span>(<span class="dv">90</span>, <span class="dv">85</span>, <span class="dv">85</span>, <span class="dv">90</span>))
grades
<span class="co">#&gt;   names exam_1 exam_2</span>
<span class="co">#&gt; 1  John     95     90</span>
<span class="co">#&gt; 2  Juan     80     85</span>
<span class="co">#&gt; 3  Jean     90     85</span>
<span class="co">#&gt; 4   Yao     85     90</span></code></pre></div>
<p><em>Warning</em>: By default the function <code>data.frame</code> coerces characters into factors:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(grades<span class="op">$</span>names)
<span class="co">#&gt; [1] &quot;factor&quot;</span></code></pre></div>
<p>To avoid this we use the rather cumbersome argument <code>stringsAsFactors</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">grades &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">names =</span> <span class="kw">c</span>(<span class="st">&quot;John&quot;</span>, <span class="st">&quot;Juan&quot;</span>, <span class="st">&quot;Jean&quot;</span>, <span class="st">&quot;Yao&quot;</span>), 
                     <span class="dt">exam_1 =</span> <span class="kw">c</span>(<span class="dv">95</span>, <span class="dv">80</span>, <span class="dv">90</span>, <span class="dv">85</span>), 
                     <span class="dt">exam_2 =</span> <span class="kw">c</span>(<span class="dv">90</span>, <span class="dv">85</span>, <span class="dv">85</span>, <span class="dv">90</span>),
                     <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)
<span class="kw">class</span>(grades<span class="op">$</span>names)
<span class="co">#&gt; [1] &quot;character&quot;</span></code></pre></div>
</div>
<div id="exercises-5" class="section level3 unnumbered">
<h3>Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Load the <code>dplyr</code> package and the murders dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(dslabs)
<span class="kw">data</span>(murders)</code></pre></div>
<p>You can add columns using the <code>dplyr</code> function <code>mutate</code>. This function is aware of the column names and inside the function you can call them unquoted. Like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders &lt;-<span class="st"> </span><span class="kw">mutate</span>(murders, <span class="dt">population_in_millions =</span> population <span class="op">/</span><span class="st"> </span><span class="dv">10</span><span class="op">^</span><span class="dv">6</span>)</code></pre></div>
<p>Note that we can write <code>population</code> rather than <code>murders$population</code>. The function <code>mutate</code> knows we are grabing columns from <code>murders</code>.</p>
<p>Use the function <code>mutate</code> to add a murders column named <code>rate</code> with the per 100,000 murder rate. Make sure you redefine <code>murders</code> as done in the example code above and remember the murder rate is defined the total divided by the population size times 100,000.</p></li>
<li><p>Note that if <code>rank(x)</code> gives you the ranks of <code>x</code> from lowest to highest, <code>rank(-x)</code> gives you the ranks from highest to lowest. Use the function <code>mutate</code> to add a column <code>rank</code> containing the rank, from highest to lowest murder rate. Make sure you redeinfe murders.</p></li>
<li><p>With <code>dplyr</code> we can use <code>select</code> to show only certain columns. For example with this code we would only show the states and population sizes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(murders, state, population) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()
<span class="co">#&gt;        state population</span>
<span class="co">#&gt; 1    Alabama    4779736</span>
<span class="co">#&gt; 2     Alaska     710231</span>
<span class="co">#&gt; 3    Arizona    6392017</span>
<span class="co">#&gt; 4   Arkansas    2915918</span>
<span class="co">#&gt; 5 California   37253956</span>
<span class="co">#&gt; 6   Colorado    5029196</span></code></pre></div>
<p>Use <code>select</code> to show the state names and abbreviations in <code>murders</code>. Just show it, do not define a new object.</p>
<p>Hint: You can use select to just show one or more columns like this</p></li>
<li><p>The <code>dplyr</code> function <code>filter</code> is used to choose specific rows of the data frame to keep. Unlke <code>select</code> which is for columns, <code>filter</code> is for rows. For example you can show just New York row like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(murders, state <span class="op">==</span><span class="st"> &quot;New York&quot;</span>)
<span class="co">#&gt;      state abb    region population total rate</span>
<span class="co">#&gt; 1 New York  NY Northeast   19378102   517 2.67</span></code></pre></div>
<p>You can use other logical vector to filter rows.</p>
<p>Use <code>filter</code> to show the top 5 states with the highest murder rates. After we add murder rate and rank, do not change the murders dataset, just show the result. Note that you can filter based on the <code>rank</code> column.</p></li>
<li><p>We can remove rows using the <code>!=</code> operator. For example to remove Florida we would do this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">no_florida &lt;-<span class="st"> </span><span class="kw">filter</span>(murders, state <span class="op">!=</span><span class="st"> &quot;Florida&quot;</span>)</code></pre></div>
<p>Create a new data frame called <code>no_south</code> that removes states from the South region. How many states are in this category? You can use the function <code>nrow</code> for this.</p></li>
<li><p>We can also use the <code>%in%</code> to filter with <code>dplyr</code>. For example you can see the data from New York and Texas like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(murders, state <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;New York&quot;</span>, <span class="st">&quot;Texas&quot;</span>))
<span class="co">#&gt;      state abb    region population total rate</span>
<span class="co">#&gt; 1 New York  NY Northeast   19378102   517 2.67</span>
<span class="co">#&gt; 2    Texas  TX     South   25145561   805 3.20</span></code></pre></div>
<p>Create a new data frame called <code>murders_nw</code> with only the states from the Northeast and the West. How many states are in this category?</p></li>
<li><p>Suppose you want to live in the Northeast or West <strong>and</strong> want the murder rate to be less than 1. We want to see the data for the states satisfying these options. Note that you can use logical operators with <code>filter</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(murders, population <span class="op">&lt;</span><span class="st"> </span><span class="dv">5000000</span> <span class="op">&amp;</span><span class="st"> </span>region <span class="op">==</span><span class="st"> &quot;Northeast&quot;</span>)
<span class="co">#&gt;           state abb    region population total  rate</span>
<span class="co">#&gt; 1   Connecticut  CT Northeast    3574097    97 2.714</span>
<span class="co">#&gt; 2         Maine  ME Northeast    1328361    11 0.828</span>
<span class="co">#&gt; 3 New Hampshire  NH Northeast    1316470     5 0.380</span>
<span class="co">#&gt; 4  Rhode Island  RI Northeast    1052567    16 1.520</span>
<span class="co">#&gt; 5       Vermont  VT Northeast     625741     2 0.320</span></code></pre></div>
<p>Add a murder rate column and a rank column as done before. Create a table, call it <code>my_states</code>, that satisfies both the conditions: it is in the Northeast or West and the murder rate is less than 1. Use select to show only the state name, the rate and the rank.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(dslabs)
<span class="kw">data</span>(murders)</code></pre></div></li>
<li><p>The pipe <code>%&gt;%</code> can be used to perform operations sequentially without having to define intermediate objects. After redefining murder to include rate and rank.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
murders &lt;-<span class="st"> </span><span class="kw">mutate</span>(murders, <span class="dt">rate =</span>  total <span class="op">/</span><span class="st"> </span>population <span class="op">*</span><span class="st"> </span><span class="dv">100000</span>, <span class="dt">rank =</span> (<span class="op">-</span>rate))</code></pre></div>
<p>in the solution to the previous exercise we did the following:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Created a table </span>
my_states &lt;-<span class="st"> </span><span class="kw">filter</span>(murders, region <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Northeast&quot;</span>, <span class="st">&quot;West&quot;</span>) <span class="op">&amp;</span><span class="st"> </span>rate <span class="op">&lt;</span><span class="st"> </span><span class="dv">1</span>)

<span class="co"># Used select to show only the state name, the murder rate and the rank</span>
<span class="kw">select</span>(my_states, state, rate, rank)
<span class="co">#&gt;           state  rate   rank</span>
<span class="co">#&gt; 1        Hawaii 0.515 -0.515</span>
<span class="co">#&gt; 2         Idaho 0.766 -0.766</span>
<span class="co">#&gt; 3         Maine 0.828 -0.828</span>
<span class="co">#&gt; 4 New Hampshire 0.380 -0.380</span>
<span class="co">#&gt; 5        Oregon 0.940 -0.940</span>
<span class="co">#&gt; 6          Utah 0.796 -0.796</span>
<span class="co">#&gt; 7       Vermont 0.320 -0.320</span>
<span class="co">#&gt; 8       Wyoming 0.887 -0.887</span></code></pre></div>
<p>The pipe <code>%&gt;%</code> permits us to perform both operation sequentially and without having to define an intermediate variable <code>my_states</code>. For example we could have mutated and selected in the same line like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mutate</span>(murders, <span class="dt">rate =</span>  total <span class="op">/</span><span class="st"> </span>population <span class="op">*</span><span class="st"> </span><span class="dv">100000</span>, <span class="dt">rank =</span> (<span class="op">-</span>rate)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(state, rate, rank)
<span class="co">#&gt;                   state   rate    rank</span>
<span class="co">#&gt; 1               Alabama  2.824  -2.824</span>
<span class="co">#&gt; 2                Alaska  2.675  -2.675</span>
<span class="co">#&gt; 3               Arizona  3.630  -3.630</span>
<span class="co">#&gt; 4              Arkansas  3.189  -3.189</span>
<span class="co">#&gt; 5            California  3.374  -3.374</span>
<span class="co">#&gt; 6              Colorado  1.292  -1.292</span>
<span class="co">#&gt; 7           Connecticut  2.714  -2.714</span>
<span class="co">#&gt; 8              Delaware  4.232  -4.232</span>
<span class="co">#&gt; 9  District of Columbia 16.453 -16.453</span>
<span class="co">#&gt; 10              Florida  3.398  -3.398</span>
<span class="co">#&gt; 11              Georgia  3.790  -3.790</span>
<span class="co">#&gt; 12               Hawaii  0.515  -0.515</span>
<span class="co">#&gt; 13                Idaho  0.766  -0.766</span>
<span class="co">#&gt; 14             Illinois  2.837  -2.837</span>
<span class="co">#&gt; 15              Indiana  2.190  -2.190</span>
<span class="co">#&gt; 16                 Iowa  0.689  -0.689</span>
<span class="co">#&gt; 17               Kansas  2.208  -2.208</span>
<span class="co">#&gt; 18             Kentucky  2.673  -2.673</span>
<span class="co">#&gt; 19            Louisiana  7.743  -7.743</span>
<span class="co">#&gt; 20                Maine  0.828  -0.828</span>
<span class="co">#&gt; 21             Maryland  5.075  -5.075</span>
<span class="co">#&gt; 22        Massachusetts  1.802  -1.802</span>
<span class="co">#&gt; 23             Michigan  4.179  -4.179</span>
<span class="co">#&gt; 24            Minnesota  0.999  -0.999</span>
<span class="co">#&gt; 25          Mississippi  4.044  -4.044</span>
<span class="co">#&gt; 26             Missouri  5.360  -5.360</span>
<span class="co">#&gt; 27              Montana  1.213  -1.213</span>
<span class="co">#&gt; 28             Nebraska  1.752  -1.752</span>
<span class="co">#&gt; 29               Nevada  3.110  -3.110</span>
<span class="co">#&gt; 30        New Hampshire  0.380  -0.380</span>
<span class="co">#&gt; 31           New Jersey  2.798  -2.798</span>
<span class="co">#&gt; 32           New Mexico  3.254  -3.254</span>
<span class="co">#&gt; 33             New York  2.668  -2.668</span>
<span class="co">#&gt; 34       North Carolina  2.999  -2.999</span>
<span class="co">#&gt; 35         North Dakota  0.595  -0.595</span>
<span class="co">#&gt; 36                 Ohio  2.687  -2.687</span>
<span class="co">#&gt; 37             Oklahoma  2.959  -2.959</span>
<span class="co">#&gt; 38               Oregon  0.940  -0.940</span>
<span class="co">#&gt; 39         Pennsylvania  3.598  -3.598</span>
<span class="co">#&gt; 40         Rhode Island  1.520  -1.520</span>
<span class="co">#&gt; 41       South Carolina  4.475  -4.475</span>
<span class="co">#&gt; 42         South Dakota  0.983  -0.983</span>
<span class="co">#&gt; 43            Tennessee  3.451  -3.451</span>
<span class="co">#&gt; 44                Texas  3.201  -3.201</span>
<span class="co">#&gt; 45                 Utah  0.796  -0.796</span>
<span class="co">#&gt; 46              Vermont  0.320  -0.320</span>
<span class="co">#&gt; 47             Virginia  3.125  -3.125</span>
<span class="co">#&gt; 48           Washington  1.383  -1.383</span>
<span class="co">#&gt; 49        West Virginia  1.457  -1.457</span>
<span class="co">#&gt; 50            Wisconsin  1.706  -1.706</span>
<span class="co">#&gt; 51              Wyoming  0.887  -0.887</span></code></pre></div>
<p>Note that <code>select</code> no longer has a data frame as the first argument. The first argument is assumed to be the result of the operation conducted right before the <code>%&gt;%</code></p>
<p>Repeat the previous exercise, but now instead of creating a new object, show the result and only include the state, rate, and rank columns. Use a pipe <code>%&gt;%</code> to do this in just one line.</p></li>
<li><p>Now we will make murders the original table one gets when loading using <code>data(murders)</code>. Use just one line to create a new data frame, called, <code>my_states</code> that has murder rate and rank column, consider only states in the Northeast or West, which have a murder rate lower than 1 and contain only the state, rate, and rank columns. The line should have four components separated by three <code>%&gt;%</code>.</p>
<ul>
<li>The original dataset <code>murders</code></li>
<li>A call to <code>mutate</code> to add the murder rate and the rank.</li>
<li>A call to <code>filter</code> to keep only the states from the Northeast or West and that have a murder rate below 1</li>
<li>A call to <code>select</code> that keeps only the columns with the stata name, the murder rate and the rank.</li>
</ul>
<p>The line should look something like this <code>my_states &lt;- murders %&gt;%</code> mutate something <code>%&gt;%</code> filter something <code>%&gt;%</code> select something.</p></li>
</ol>

</div>
</div>
<div id="basic-plots" class="section level2">
<h2><span class="header-section-number">1.12</span> Basic plots</h2>
<p>Exploratory data visualization is perhaps the strength of R. One can quickly go from idea to data to plot with a unique balance of flexibility and ease. For example, Excel may be easier than R, but it is nowhere near as flexible. D3.js may be more flexible and powerful than R, but it takes much longer to generate a plot. Before we focus on data visualization in the next chapter, we first we want to introduce some very basic plotting functions.</p>
<div id="scatter-plots" class="section level3">
<h3><span class="header-section-number">1.12.1</span> Scatter plots</h3>
<p>Earlier we inferred that states with larger populations are likely to have more murders. This can be confirmed with an exploratory visualization that plots these two quantities against each other:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">population_in_millions &lt;-<span class="st"> </span>murders<span class="op">$</span>population<span class="op">/</span><span class="dv">10</span><span class="op">^</span><span class="dv">6</span>
total_gun_murders &lt;-<span class="st"> </span>murders<span class="op">$</span>total
<span class="kw">plot</span>(population_in_millions, total_gun_murders)</code></pre></div>
<p><img src="book_files/figure-html/first-plot-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>We can clearly see a relationship. <strong>Advanced</strong>: For a quick plot that avoids accessing variables twice, we can use the <code>with</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">with</span>(murders, <span class="kw">plot</span>(population, total))</code></pre></div>
</div>
<div id="histograms" class="section level3">
<h3><span class="header-section-number">1.12.2</span> Histograms</h3>
<p>We will describe histograms as they relate to distribution in the next chapter. Here we will simply note that histograms are a powerful graphical summary of a list of numbers that gives you a general overview of the types of values you have. We can make a histogram of our murder rates by simply typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(murders<span class="op">$</span>rate)</code></pre></div>
<p><img src="book_files/figure-html/r-base-hist-1.png" width="70%" style="display: block; margin: auto;" /> We can see that there is a wide range of values with most of them between 2 and 3 and one very extreme case with a murder rate of more than 15:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">murders<span class="op">$</span>state[<span class="kw">which.max</span>(murders<span class="op">$</span>rate)]
<span class="co">#&gt; [1] &quot;District of Columbia&quot;</span></code></pre></div>
</div>
<div id="boxplot" class="section level3">
<h3><span class="header-section-number">1.12.3</span> Boxplot</h3>
<p>Boxplots will be described in more detail in the next chapter as well. Boxplots provide a more terse summary than histograms, but they are easier to stack with other boxplots. For example, here we can use them to compare the different regions:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(rate<span class="op">~</span>region, <span class="dt">data =</span> murders)</code></pre></div>
<p><img src="book_files/figure-html/r-base-boxplot-1.png" width="70%" style="display: block; margin: auto;" /> We can see that the South has larger murder rates than the other three regions.</p>
</div>
<div id="exercises-6" class="section level3 unnumbered">
<h3>Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>We made a plot of total murders versus population and noted a strong relationship: not surprisingly states with larger populations had more murders.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dslabs)
<span class="kw">data</span>(murders)
population_in_millions &lt;-<span class="st"> </span>murders<span class="op">$</span>population<span class="op">/</span><span class="dv">10</span><span class="op">^</span><span class="dv">6</span>
total_gun_murders &lt;-<span class="st"> </span>murders<span class="op">$</span>total
<span class="kw">plot</span>(population_in_millions, total_gun_murders)</code></pre></div>
<p>Keep in mind that many states have populations below 5 million and are bunched up. We may gain further insights from making this plot in the log scale. Transform the variables using the <code>log10</code> transformation and then plot them.</p></li>
<li><p>Create a histogram of the state populations.</p></li>
<li><p>Generate boxplots of the state populations by region.</p></li>
</ol>

</div>
</div>
<div id="importing-data" class="section level2">
<h2><span class="header-section-number">1.13</span> Importing Data</h2>
<p>In this chapter we used a data set already stored in an R object. A data scientist will rarely have such luck and will have to import data into R from either a file, a database, or other source. We cover this in more detail in Chapter 7. But because it is so common to read data from a file, we will briefly describe the key approach and function, in case you want to use your new knowledge on one of your own datasets.</p>
<p>Small datasets such as the one used in this chapter are commonly stored as Excel files. Although there are R packages designed to read Excel (xls) format, you generally want to avoid this format and save files as comma delimited (Comma-Separated Value/CSV) or tab delimited (Tab-Separated Value/TSV/TXT) files. These plain-text formats make it easier to share data since commercial software is not required for working with the data.</p>
<div id="paths-and-the-working-directory" class="section level4">
<h4><span class="header-section-number">1.13.0.1</span> Paths and the working directory</h4>
<p>The first step is to find the file containing your data and know its <em>path</em>. When you are working in R it is useful to know your <em>working directory</em>. This is the folder in which R will save or look for files by default. You can see your working directory by typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">getwd</span>()</code></pre></div>
<p>You can also change your working directory using the function <code>setwd</code>. Or you can change it through RStudio by clicking on “Session”.</p>
<p>The functions that read and write files (there are several in R) assume you mean to look for files or write files in the working directory. Our recommended approach for beginners will have you reading and writing to the working directory. However, you can also type the <a href="http://www.computerhope.com/jargon/a/absopath.htm">full path</a>, which will work independently of the working directory.</p>
<p>We have included the US murders data in CSV file as part of the <code>dslabs</code> package. We recommend placing your data in your working directory.</p>
<p>Because knowing where packages store files is rather advanced, we provide the following code that finds the directory and copies the file:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dir &lt;-<span class="st"> </span><span class="kw">system.file</span>(<span class="dt">package=</span><span class="st">&quot;dslabs&quot;</span>) <span class="co">#extracts the location of package</span>
filename &lt;-<span class="st"> </span><span class="kw">file.path</span>(dir,<span class="st">&quot;extdata/murders.csv&quot;</span>)
<span class="kw">file.copy</span>(filename, <span class="st">&quot;murders.csv&quot;</span>)
<span class="co">#&gt; [1] TRUE</span></code></pre></div>
<p>You should be able to see the file in your working directory and can check using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list.files</span>()
<span class="co">#&gt;  [1] &quot;_bookdown.yml&quot; &quot;_common.R&quot;     &quot;_output.yml&quot;   &quot;book_cache&quot;   </span>
<span class="co">#&gt;  [5] &quot;book_files&quot;    &quot;book.bib&quot;      &quot;book.Rmd&quot;      &quot;dataviz&quot;      </span>
<span class="co">#&gt;  [9] &quot;docs&quot;          &quot;dsbook.Rproj&quot;  &quot;index.Rmd&quot;     &quot;intro&quot;        </span>
<span class="co">#&gt; [13] &quot;murders.csv&quot;   &quot;packages.bib&quot;  &quot;preamble.tex&quot;  &quot;R&quot;            </span>
<span class="co">#&gt; [17] &quot;README.md&quot;     &quot;style.css&quot;</span></code></pre></div>
</div>
<div id="read.csv" class="section level3">
<h3><span class="header-section-number">1.13.1</span> <code>read.csv</code></h3>
<p>We are ready to read in the file. There are several functions for reading in tables. Here we introduce one included in base R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;murders.csv&quot;</span>)
<span class="kw">head</span>(dat)
<span class="co">#&gt;        state abb region population total</span>
<span class="co">#&gt; 1    Alabama  AL  South    4779736   135</span>
<span class="co">#&gt; 2     Alaska  AK   West     710231    19</span>
<span class="co">#&gt; 3    Arizona  AZ   West    6392017   232</span>
<span class="co">#&gt; 4   Arkansas  AR  South    2915918    93</span>
<span class="co">#&gt; 5 California  CA   West   37253956  1257</span>
<span class="co">#&gt; 6   Colorado  CO   West    5029196    65</span></code></pre></div>
<p>We can see that we have read in the file.</p>
<p>Warning: <code>read.csv</code> automatically converts characters to factors. Note for example that:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(dat<span class="op">$</span>state)
<span class="co">#&gt; [1] &quot;factor&quot;</span></code></pre></div>
<p>You can avoid this using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;murders.csv&quot;</span>, <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)
<span class="kw">class</span>(dat<span class="op">$</span>state)
<span class="co">#&gt; [1] &quot;character&quot;</span></code></pre></div>
<p>With this call the region variable is no longer a factor, but we can easily change this with:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">mutate</span>(dat, <span class="dt">region =</span>  <span class="kw">as.factor</span>(region))</code></pre></div>
<p>Now that we are done with this example we remove the <code>murders.csv</code> file from our working directory</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">file.remove</span>(<span class="st">&quot;murders.csv&quot;</span>)
<span class="co">#&gt; [1] TRUE</span></code></pre></div>

</div>
</div>
<div id="programming-basics" class="section level2">
<h2><span class="header-section-number">1.14</span> Programming basics</h2>
<p>We teach R because it greatly facilitates data analysis, the main topic of this book. By coding in R, we can efficiently perform exploratory data analysis, build data analysis pipelines and prepare data visualization to communicate results. However R is not just a data analysis environment but a programming language. Advanced R programmers can develop complex packages and even improve R itself, but we do not cover advanced programming in this book. Nonetheless, in this section we introduce three key programming concepts: conditional expressions, for-loops and functions. These are not just key building blocks for advanced programming, but are sometimes useful during data analysis. We also provide a list of power functions that we do not cover in the book but are worth exploring since they are powerful tools commonly used by expert data analysts.</p>
<div id="conditionals-expressions" class="section level3">
<h3><span class="header-section-number">1.14.1</span> Conditionals expressions</h3>
<p>Conditional expressions are one of the basic features of programming. They are used for what is called <em>flow control</em>. The most common conditional expression is the if-else statement. In R, we can actually perform quite a bit of data analysis without conditionals. However, they do come up occasionally and once you start writing your own functions and packages, you will need them.</p>
<p>Here is a very simple example showing the general structure of an if-else statement. The basic idea is to print the reciprocal of <code>a</code> unless <code>a</code> is 0:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="dv">0</span>

<span class="cf">if</span>(a<span class="op">!=</span><span class="dv">0</span>){
  <span class="kw">print</span>(<span class="dv">1</span><span class="op">/</span>a)
} <span class="cf">else</span>{
  <span class="kw">print</span>(<span class="st">&quot;No reciprocal for 0.&quot;</span>)
}
<span class="co">#&gt; [1] &quot;No reciprocal for 0.&quot;</span></code></pre></div>
<p>Let’s look at one more example using the US murders data frame:</p>
<p>Here is a very simple example that tells us which states, if any, have a murder rate lower than 0.5 per 100,000. The if statement protects us from the case in which no state satisfies the condition.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind &lt;-<span class="st"> </span><span class="kw">which.min</span>(murder_rate)

<span class="cf">if</span>(murder_rate[ind] <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.5</span>){
  <span class="kw">print</span>(murders<span class="op">$</span>state[ind]) 
} <span class="cf">else</span>{
  <span class="kw">print</span>(<span class="st">&quot;No state has murder rate that low&quot;</span>)
}
<span class="co">#&gt; [1] &quot;Vermont&quot;</span></code></pre></div>
<p>If we try it again with a rate of 0.25 we get a different answer:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">if</span>(murder_rate[ind] <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.25</span>){
  <span class="kw">print</span>(murders<span class="op">$</span>state[ind]) 
} <span class="cf">else</span>{
  <span class="kw">print</span>(<span class="st">&quot;No state has a murder rate that low.&quot;</span>)
}
<span class="co">#&gt; [1] &quot;No state has a murder rate that low.&quot;</span></code></pre></div>
<p>A related function that is very useful is <code>ifelse</code>. This function takes three arguments: a logical and two possible answers. If the logical is <code>TRUE</code> the value in the second argument is returned and if <code>FALSE</code> the value in the third argument is returned. Here is an example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="dv">0</span>
<span class="kw">ifelse</span>(a <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="dv">1</span><span class="op">/</span>a, <span class="ot">NA</span>)
<span class="co">#&gt; [1] NA</span></code></pre></div>
<p>The function is particularly useful because it works on vectors. It examines each entry of the logical vector and returns elements from the vector provided in the second argument if the entry is <code>TRUE</code> or elements from the vector provided in the third argument if the entry is <code>FALSE</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="op">-</span><span class="dv">4</span>,<span class="dv">5</span>)
result &lt;-<span class="st"> </span><span class="kw">ifelse</span>(a <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="dv">1</span><span class="op">/</span>a, <span class="ot">NA</span>)</code></pre></div>
<p>This table helps us see what happened:</p>
<table>
<thead>
<tr class="header">
<th align="right">a</th>
<th align="left">is_a_positive</th>
<th align="right">answer1</th>
<th align="left">answer2</th>
<th align="right">result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="left">FALSE</td>
<td align="right">Inf</td>
<td align="left">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">TRUE</td>
<td align="right">1.00</td>
<td align="left">NA</td>
<td align="right">1.0</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="left">TRUE</td>
<td align="right">0.50</td>
<td align="left">NA</td>
<td align="right">0.5</td>
</tr>
<tr class="even">
<td align="right">-4</td>
<td align="left">FALSE</td>
<td align="right">-0.25</td>
<td align="left">NA</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">TRUE</td>
<td align="right">0.20</td>
<td align="left">NA</td>
<td align="right">0.2</td>
</tr>
</tbody>
</table>
<p>Here is an example of how this function can be readily used to replace all the missing values in a vector with zeros:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(na_example)
no_nas &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">is.na</span>(na_example), <span class="dv">0</span>, na_example) 
<span class="kw">sum</span>(<span class="kw">is.na</span>(no_nas))
<span class="co">#&gt; [1] 0</span></code></pre></div>
<p>Two other useful functions are <code>any</code> and <code>all</code>. The <code>any</code> function takes a vector of logicals and returns <code>TRUE</code> if any of the entries is <code>TRUE</code>. The <code>all</code> function takes a vector of logicals and returns <code>TRUE</code> if all of the entries are <code>TRUE</code>. Here is an example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>)
<span class="kw">any</span>(z)
<span class="co">#&gt; [1] TRUE</span>
<span class="kw">all</span>(z)
<span class="co">#&gt; [1] FALSE</span></code></pre></div>
</div>
<div id="defining-functions" class="section level3">
<h3><span class="header-section-number">1.14.2</span> Defining functions</h3>
<p>As you become more experienced, you will find yourself needing to perform the same operations over and over. A simple example is computing averages. We can compute the average of a vector <code>x</code> using the <code>sum</code> and <code>length</code> functions: <code>sum(x)/length(x)</code>. But because we do this repeatedly, it is much more efficient to write a function that performs this operation. This particular operation is so common that someone already wrote the <code>mean</code> function and it is included in base R. However, you will encounter situations in which the function does not already exist so R permits you to write your own. A simple version of function that computes the average can be defined like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">avg &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  s &lt;-<span class="st"> </span><span class="kw">sum</span>(x)
  n &lt;-<span class="st"> </span><span class="kw">length</span>(x)
  s<span class="op">/</span>n
}</code></pre></div>
<p>Now <code>avg</code> is a function that computes the mean:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">100</span>
<span class="kw">identical</span>(<span class="kw">mean</span>(x), <span class="kw">avg</span>(x))
<span class="co">#&gt; [1] TRUE</span></code></pre></div>
<p>Notice that variables defined inside a function are not saved in the workspace. So while we use <code>s</code> and <code>n</code> when we call <code>avg</code>, the values are created and changed only during the call. Here is an illustrative example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">s &lt;-<span class="st"> </span><span class="dv">3</span>
<span class="kw">avg</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>)
<span class="co">#&gt; [1] 5.5</span>
s
<span class="co">#&gt; [1] 3</span></code></pre></div>
<p>Note how <code>s</code> is still 3 after we call <code>avg</code>.</p>
<p>In general, functions are objects, so we assign them to variable names with <code>&lt;-</code>. The function <code>function</code> tells R you are about to define a function. The general form of a function definition looks like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">my_function &lt;-<span class="st"> </span><span class="cf">function</span>(VARIABLE_NAME){
  perform operations on VARIABLE_NAME and calculate VALUE
  VALUE
}</code></pre></div>
<p>The functions you define can have multiple arguments as well as default values. For example, we can define a function that computes either the arithmetic or geometric average depending on a user defined variable like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">avg &lt;-<span class="st"> </span><span class="cf">function</span>(x, <span class="dt">arithmetic =</span> <span class="ot">TRUE</span>){
  n &lt;-<span class="st"> </span><span class="kw">length</span>(x)
  <span class="kw">ifelse</span>(arithmetic, <span class="kw">sum</span>(x)<span class="op">/</span>n, <span class="kw">prod</span>(x)<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span>n))
}</code></pre></div>
<p>We will learn more about how to create functions through experience as we face more complex tasks.</p>
</div>
<div id="for-loops" class="section level3">
<h3><span class="header-section-number">1.14.3</span> For loops</h3>
<p>The formula for the sum <span class="math inline">\(1+2+\dots+n\)</span> is <span class="math inline">\(n(n+1)/2\)</span>. What if we weren’t sure that was the right function? How could we check? Using what we learned about functions we can create one that computes the <span class="math inline">\(S_n\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">compute_s_n &lt;-<span class="st"> </span><span class="cf">function</span>(n){
  x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span>n
  <span class="kw">sum</span>(x)
}</code></pre></div>
<p>Now if we can compute <span class="math inline">\(S_n\)</span> for various vales of <span class="math inline">\(n\)</span>, say <span class="math inline">\(n=1,\dots,25\)</span> how do we do it? Do we write 25 lines of code calling <code>compute_s_n</code>? No, that is what for loops are for in programming. In this case, we are performing exactly the same task over and over and the only thing that is changing is the value of <span class="math inline">\(n\)</span>. For loops let us define the range that our variable takes (in our example <span class="math inline">\(n=1,\dots,10\)</span>), then change the value as you <em>loop</em> and evaluate expression as you loop.</p>
<p>Perhaps the simplest example of a for loop is this useless piece of code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>){
  <span class="kw">print</span>(i)
}
<span class="co">#&gt; [1] 1</span>
<span class="co">#&gt; [1] 2</span>
<span class="co">#&gt; [1] 3</span>
<span class="co">#&gt; [1] 4</span>
<span class="co">#&gt; [1] 5</span></code></pre></div>
<p>And here is the for loop we would write for our <span class="math inline">\(S_n\)</span> example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m &lt;-<span class="st"> </span><span class="dv">25</span>
s_n &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">length =</span> m) <span class="co"># create an empty vector</span>
<span class="cf">for</span>(n <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>m){
  s_n[n] &lt;-<span class="st"> </span><span class="kw">compute_s_n</span>(n)
}</code></pre></div>
<p>In each iteration <span class="math inline">\(n=1\)</span>, <span class="math inline">\(n=2\)</span>, etc…, we compute <span class="math inline">\(S_n\)</span> and store it in the <span class="math inline">\(n\)</span>th entry of <code>s_n</code>.</p>
<p>Now we can create a plot to search for a pattern:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span>m
<span class="kw">plot</span>(n, s_n)</code></pre></div>
<p><img src="book_files/figure-html/sum-of-consecutive-squares-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>If you noticed that it appears to be a quadratic, you are on the right track because the formula is <span class="math inline">\(n(n+1)/2\)</span> which we can confirm with a table:</p>
<pre><code>#&gt;   s_n formula
#&gt; 1   1       1
#&gt; 2   3       3
#&gt; 3   6       6
#&gt; 4  10      10
#&gt; 5  15      15
#&gt; 6  21      21</code></pre>
<p>We can also overlay the two results by using the function <code>lines</code> to draw a line over the previously plotted points:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(n, s_n)
<span class="kw">lines</span>(n, n<span class="op">*</span>(n<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span><span class="dv">2</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-181-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<div id="vectorization-and-functionals" class="section level3">
<h3><span class="header-section-number">1.14.4</span> Vectorization and Functionals</h3>
<p>Although for-loop are an important concept to understand, in R we rarely use them. As you learn more R you will realize that <em>vectorization</em> is the prefered over for-loops as it results in shorter and clearer code. We already saw examples in the Vector Arithmetic Section. A <em>vectorized</em> function is a function that will apply the same operation on each of the vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span>
<span class="kw">sqrt</span>(x)
<span class="co">#&gt;  [1] 1.00 1.41 1.73 2.00 2.24 2.45 2.65 2.83 3.00 3.16</span>
y &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span>
x<span class="op">*</span>y
<span class="co">#&gt;  [1]   1   4   9  16  25  36  49  64  81 100</span></code></pre></div>
<p>No need for for-loops. But not all functions work this way. For instance, the function we just wrote, <code>compute_s_n</code> does not work element-wise since it is expecting a scalar. This piece of code does not run the function on each entry of <code>n</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">25</span>
<span class="kw">compute_s_n</span>(n)</code></pre></div>
<p>Functionals are function that help us apply the same function each entry in a vector, matrix, data frame or list. Here we cover the functional that operates on numeric, logical and character vectors: <code>sapply</code>. This is similar to whatSimilar to what we can do in a</p>
<p>The function <code>sapply</code> permits us to perform element-wise operations on any function. Here is how it works:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span>
<span class="kw">sapply</span>(x, sqrt)
<span class="co">#&gt;  [1] 1.00 1.41 1.73 2.00 2.24 2.45 2.65 2.83 3.00 3.16</span></code></pre></div>
<p>Here each element of <code>x</code> is passed on to the function <code>sqrt</code> and the result is returned. These results are concatenated. In this case, the resulting is a vector of the same length as the original <code>x</code>. This implies that the for loop above can be written like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">25</span>
s_n &lt;-<span class="st"> </span><span class="kw">sapply</span>(n, compute_s_n)
<span class="kw">plot</span>(n, s_n)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-185-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>Other functionals are <code>apply</code>, <code>lapply</code>, <code>tapply</code>, <code>mapply</code>,<code>vapply</code>, and <code>replicate</code>. We only use <code>sapply</code> and <code>replicate</code> in this book but we recommend becoming familiar with the others as they can be very useful.</p>
</div>
<div id="map" class="section level3">
<h3><span class="header-section-number">1.14.5</span> map</h3>
<p>Another series of fuctionals are provided by the purrr package. These are similar to <code>sapply</code> but they are somewhat easier to use for begginers in some instance. The general idea is the same</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(purrr)
n &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">25</span>
s_n &lt;-<span class="st"> </span><span class="kw">map</span>(n, compute_s_n)</code></pre></div>
<p>One advantage that becomes clear latter is that with the purrr functionals you know what type of object you will get back. This is different with <code>sapply</code> that can return several different types. The <code>map</code> function always returns a list.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(s_n)
<span class="co">#&gt; [1] &quot;list&quot;</span></code></pre></div>
<p>If we want a numeric vector we can instead use</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">s_n &lt;-<span class="st"> </span><span class="kw">map_dbl</span>(n, compute_s_n)
<span class="kw">plot</span>(n, s_n)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-188-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>We will learn other advantages of <code>map</code> in latter chapters.</p>
</div>
<div id="other-functions" class="section level3">
<h3><span class="header-section-number">1.14.6</span> Other functions</h3>
<p>Other functions that are widely used that we will not cover in this book are <code>split</code>, <code>cut</code>, <code>do.call</code> and <code>Reduce</code>.</p>
</div>
<div id="exercises-7" class="section level3 unnumbered">
<h3>Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>What will this conditional expression return?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="op">-</span><span class="dv">3</span>,<span class="dv">4</span>)

<span class="cf">if</span>(<span class="kw">all</span>(x<span class="op">&gt;</span><span class="dv">0</span>)){
  <span class="kw">print</span>(<span class="st">&quot;A ll Postives&quot;</span>)
} <span class="cf">else</span>{
  <span class="kw">print</span>(<span class="st">&quot;Not all positives&quot;</span>)
}
<span class="co">#&gt; [1] &quot;Not all positives&quot;</span></code></pre></div></li>
<li><p>Which of the following expressions is always <code>FALSE</code> when at least one entry of a logical vector <code>x</code> is TRUE?</p>
<p>A. <code>all(x)</code> B. <code>any(x)</code> C. <code>any(!x)</code> D. <code>all(!x)</code></p></li>
<li><p>The function <code>nchar</code> tells you how many characters long a character vector is. For example,</p>
<p>Write a line of code that assigns to the object <code>new_names</code> the state abbreviation when the state name is longer than 8 characters.</p></li>
<li><p>Create a function <code>sum_n</code> that for any given value, say <span class="math inline">\(n\)</span>, computes the sum of the integers from 1 to n (inclusive). Use the function to determine the sum of integers from 1 to 5,000.</p></li>
<li><p>Create a function <code>altman_plot</code> that takes two arguments <code>x</code> and <code>y</code> and plots the difference against the sum.</p></li>
<li><p>After running the code below, what is the value of <code>x</code>?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">3</span>
my_func &lt;-<span class="st"> </span><span class="cf">function</span>(y){
x &lt;-<span class="st"> </span><span class="dv">5</span>
y<span class="op">+</span><span class="dv">5</span>
}</code></pre></div></li>
<li><p>Write a function <code>compute_s_n</code> that for any given <span class="math inline">\(n\)</span> computes the sum <span class="math inline">\(S_n = 1^2 + 2^2 + 3^2 + \dots n^2\)</span>. Report the value of the sum when <span class="math inline">\(n=10\)</span>.</p></li>
<li><p>Now define an empty numerical vector <code>s_n</code> of size 25 using <code>s_n &lt;- vector(&quot;numeric&quot;, 25)</code> and store in the results of <span class="math inline">\(S_1, S_2, \dots S_{25}\)</span> using a for-loop.</p></li>
<li><p>Repeat exercise 8 but this time use <code>sapply</code>.</p></li>
<li><p>Repeate exercise 8 but this time use <code>map_dbl</code>.</p></li>
<li><p>Plot <span class="math inline">\(S_n\)</span> versus <span class="math inline">\(n\)</span>. Use points defined by <span class="math inline">\(n=1,\dots,25\)</span>.</p></li>
<li><p>Confirm that the formula for this sum is <span class="math inline">\(S_n= n(n+1)(2n+1)/6\)</span>.</p></li>
</ol>

</div>
</div>
<div id="matrices" class="section level2">
<h2><span class="header-section-number">1.15</span> Matrices</h2>
<p>Matrices are another type of object that are common in R. Matrices are similar to data frames in that they are two dimensional: they have rows and columns. However, like numeric, character and logical vectors, entries in a matrices have to be all the same type. For this reason data frames are much more useful for storing data, since we can have characters, factors and numbers in them.</p>
<p>However, matrices have a major advantage over data frames and it’s that we can perform a very powerful type of mathematics operations with them called matrix algebra. We do not describe these operations in this book, but much of what happens in the background when you perform a data analysis involves matrices. For this reason, and other reasons, some of the functions we will learn return matrices so we describe them briefly here.</p>
<p>One way matrices show up is if a function called with <code>sapply</code> returns two or more values. For example suppose we write a function that for any number <code>x</code> returns <code>x</code>, <code>x^2</code> and <code>x^3</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cubic &lt;-<span class="st"> </span><span class="cf">function</span>(x) {
  <span class="kw">c</span>(x, x<span class="op">^</span><span class="dv">2</span>, x<span class="op">^</span><span class="dv">3</span>)
}
<span class="kw">cubic</span>(<span class="dv">2</span>)
<span class="co">#&gt; [1] 2 4 8</span></code></pre></div>
<p>If we use <code>sapply</code> to compute these three numbers for each of the elements in a vector, R automatically <em>binds</em> the results as columns in a matrix:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">5</span>)
mat &lt;-<span class="st"> </span><span class="kw">sapply</span>(n, cubic)
mat
<span class="co">#&gt;      [,1] [,2] [,3] [,4] [,5]</span>
<span class="co">#&gt; [1,]    1    2    3    4    5</span>
<span class="co">#&gt; [2,]    1    4    9   16   25</span>
<span class="co">#&gt; [3,]    1    8   27   64  125</span></code></pre></div>
<div id="accessing-matrix-values" class="section level3">
<h3><span class="header-section-number">1.15.1</span> Accessing matrix values</h3>
<p>You can access specific entries in a matrix using <code>[</code>. If you want the second row, third column you use</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[<span class="dv">2</span>,<span class="dv">3</span>]
<span class="co">#&gt; [1] 9</span></code></pre></div>
<p>If you want the entire second row, you leave the column spot empty:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[<span class="dv">2</span>, ]
<span class="co">#&gt; [1]  1  4  9 16 25</span></code></pre></div>
<p>Note that this returns a vector, not a matrix.</p>
<p>Similarly, if you want the entire third column you leave the row spot entry:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[ ,<span class="dv">3</span>]
<span class="co">#&gt; [1]  3  9 27</span></code></pre></div>
<p>This is also a vector, not a matrix.</p>
<p>You can access more than one column or more than one row if you want. This will give you a new matrix.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[ ,<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>]
<span class="co">#&gt;      [,1] [,2] [,3]</span>
<span class="co">#&gt; [1,]    2    3    4</span>
<span class="co">#&gt; [2,]    4    9   16</span>
<span class="co">#&gt; [3,]    8   27   64</span></code></pre></div>
<p>You can subset both rows and columns:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>]
<span class="co">#&gt;      [,1] [,2] [,3]</span>
<span class="co">#&gt; [1,]    2    3    4</span>
<span class="co">#&gt; [2,]    4    9   16</span></code></pre></div>
<p>In some of our examples we will convert matrices into data frames so that we can, for example, use them with dplyr. For this we can use the function <code>as.data.frame</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.data.frame</span>(mat)
<span class="co">#&gt;   V1 V2 V3 V4  V5</span>
<span class="co">#&gt; 1  1  2  3  4   5</span>
<span class="co">#&gt; 2  1  4  9 16  25</span>
<span class="co">#&gt; 3  1  8 27 64 125</span></code></pre></div>
<p>Note you can also use the <code>[</code> to access rows and columns of a data frame:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&quot;murders&quot;</span>)
murders[<span class="dv">25</span>, <span class="dv">1</span>]
<span class="co">#&gt; [1] &quot;Mississippi&quot;</span>
murders[<span class="dv">2</span><span class="op">:</span><span class="dv">3</span>, ]
<span class="co">#&gt;     state abb region population total</span>
<span class="co">#&gt; 2  Alaska  AK   West     710231    19</span>
<span class="co">#&gt; 3 Arizona  AZ   West    6392017   232</span></code></pre></div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-visualization.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
